"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { logEvent, EVENT_TYPES } from "@/library/events";
import { useSeedLayout } from "@/library/useSeedLayout";
import { DynamicElement } from "@/components/DynamicElement";
import { isDataGenerationAvailable } from "@/utils/healthDataGenerator";
import { initializeDoctors } from "@/data/doctors-enhanced";
import { initializeAppointments } from "@/data/appointments-enhanced";
import { initializePrescriptions } from "@/data/prescriptions-enhanced";
import { initializeMedicalRecords } from "@/data/medical-records-enhanced";
import { withSeed } from "@/utils/seedRouting";
import { initializeDoctorReviews } from "@/data/reviews-enhanced";

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);
  const { reorderElements, getText, getElementAttributes } = useSeedLayout();
  const nav = [
    { href: "/appointments", title: "Appointments", desc: "Find a slot and book online", event: EVENT_TYPES.BROWSE_APPOINTMENTS_CLICKED },
    { href: "/doctors", title: "Doctors", desc: "Browse specialists and ratings", event: EVENT_TYPES.BROWSE_DOCTORS_CLICKED },
    { href: "/prescriptions", title: "Prescriptions", desc: "View your medications", event: EVENT_TYPES.BROWSE_PRESCRIPTIONS_CLICKED },
    { href: "/medical-records", title: "Medical Records", desc: "Upload and review files", event: EVENT_TYPES.BROWSE_MEDICAL_RECORDS_CLICKED },
  ];
  const sp = typeof window !== 'undefined' ? new URLSearchParams(window.location.search) : undefined;
  const hasSeed = !!(sp?.get('seed-structure') || sp?.get('seed'));
  const reorderedNav = hasSeed ? reorderElements(nav) : nav;

  const heroParts = [
    { key: 'title' },
    { key: 'desc' },
    { key: 'cta' },
  ];
  const orderedHero = hasSeed ? reorderElements(heroParts) : heroParts;

  useEffect(() => {
    if (!isDataGenerationAvailable()) {
      setIsLoading(false);
      return;
    }
    let mounted = true;
    // Initialize doctors first, then use them for other data types
    (async () => {
      try {
        const doctors = await initializeDoctors();
        // Now initialize other data types with the generated doctors
        await Promise.allSettled([
          initializeAppointments(doctors),
          initializePrescriptions(doctors),
          initializeMedicalRecords(doctors),
        ]);
        // Warm reviews caches for first few doctors to ensure availability in profiles
        await Promise.allSettled(
          doctors.slice(0, 6).map((d) => initializeDoctorReviews({ id: d.id, name: d.name, specialty: d.specialty }))
        );
      } catch (error) {
        console.error('Error initializing data:', error);
      } finally {
        if (mounted) setIsLoading(false);
      }
    })();
    return () => { mounted = false; };
  }, []);

  if (isDataGenerationAvailable() && isLoading) {
    return (
      <div className="container py-20 flex items-center justify-center">
        <div className="flex items-center gap-3 text-muted-foreground">
          <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
          <span>Data is being generated by AI, this may take some time…</span>
        </div>
      </div>
    );
  }

  return (
    <div className="container py-10">
      <section className="mx-auto max-w-3xl text-center">
        {orderedHero.map((part, i) => (
          <DynamicElement key={part.key} elementType={`hero-${part.key}`} as="div" index={i}>
            {part.key === 'title' && (
              <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl" {...getElementAttributes('hero-title', 0)}>
                {getText('hero-title', 'Book your doctor online')}
              </h1>
            )}
            {part.key === 'desc' && (
              <p className="mt-3 text-muted-foreground" {...getElementAttributes('hero-desc', 0)}>
                {getText('hero-desc', 'Simple, fast, and secure. Demo only — no sign-in, no backend.')}
              </p>
            )}
            {part.key === 'cta' && (
              <div className="mt-6 flex justify-center">
                <Link href={withSeed("/appointments")}>
                  <Button 
                    size="lg"
                    onClick={() => logEvent(EVENT_TYPES.BROWSE_APPOINTMENTS_CLICKED, { source: "homepage_cta_button" })}
                  >
                    {getText('hero-cta', 'Browse Appointments')}
                  </Button>
                </Link>
              </div>
            )}
          </DynamicElement>
        ))}
      </section>

      <section className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {reorderedNav.map((n, i) => (
          <DynamicElement key={n.href} elementType="nav-card" as="section" index={i}>
            <Link href={withSeed(n.href)}>
              <Card 
                className="h-full transition hover:shadow-md"
                onClick={() => logEvent(n.event, { 
                  source: "homepage_card", 
                  destination: n.href,
                  title: n.title 
                })}
              >
                <CardHeader>
                  <CardTitle>
                    {n.href === '/appointments' && getText('card-appointments-title', n.title)}
                    {n.href === '/doctors' && getText('card-doctors-title', n.title)}
                    {n.href === '/prescriptions' && getText('card-prescriptions-title', n.title)}
                    {n.href === '/medical-records' && getText('card-medical-records-title', n.title)}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    {n.href === '/appointments' && getText('card-appointments-desc', n.desc)}
                    {n.href === '/doctors' && getText('card-doctors-desc', n.desc)}
                    {n.href === '/prescriptions' && getText('card-prescriptions-desc', n.desc)}
                    {n.href === '/medical-records' && getText('card-medical-records-desc', n.desc)}
                  </p>
                </CardContent>
              </Card>
            </Link>
          </DynamicElement>
        ))}
      </section>
    </div>
  );
}
