"use client";

import { SeedLink } from "@/components/ui/SeedLink";
import { useEffect, useState, useMemo } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { logEvent, EVENT_TYPES } from "@/library/events";
import { useDynamicSystem } from "@/dynamic/shared";
import { ID_VARIANTS_MAP, CLASS_VARIANTS_MAP, TEXT_VARIANTS_MAP } from "@/dynamic/v3";
import { cn } from "@/library/utils";
import { isDataGenerationAvailable } from "@/utils/healthDataGenerator";
import { initializeDoctors } from "@/data/doctors-enhanced";
import { initializeAppointments } from "@/data/appointments-enhanced";
import { initializePrescriptions } from "@/data/prescriptions-enhanced";
import { initializeMedicalRecords } from "@/data/medical-records-enhanced";
import { initializeDoctorReviews } from "@/data/reviews-enhanced";
import { isDbLoadModeEnabled } from "@/shared/seeded-loader";
import { QuickAppointmentHero } from "@/components/quick-appointment-hero";

export default function Home() {
  const dyn = useDynamicSystem();
  const [isLoading, setIsLoading] = useState(true);
  const nav = [
    { href: "/appointments", title: "Appointments", desc: "Find a slot and book online", event: EVENT_TYPES.BROWSE_APPOINTMENTS_CLICKED },
    { href: "/doctors", title: "Doctors", desc: "Browse specialists and ratings", event: EVENT_TYPES.BROWSE_DOCTORS_CLICKED },
    { href: "/prescriptions", title: "Prescriptions", desc: "View your medications", event: EVENT_TYPES.BROWSE_PRESCRIPTIONS_CLICKED },
    { href: "/medical-records", title: "Medical Records", desc: "Upload and review files", event: EVENT_TYPES.BROWSE_MEDICAL_RECORDS_CLICKED },
  ];
  const orderedNav = useMemo(() => {
    const order = dyn.v1.changeOrderElements("home-nav", nav.length);
    return order.map((idx) => nav[idx]);
  }, [dyn.seed, nav]);

  const heroParts = [
    { key: 'title' },
    { key: 'desc' },
    { key: 'cta' },
  ];
  const orderedHero = useMemo(() => {
    const order = dyn.v1.changeOrderElements("home-hero", heroParts.length);
    return order.map((idx) => heroParts[idx]);
  }, [dyn.seed, heroParts]);
  const useAiGeneration = isDataGenerationAvailable() && !isDbLoadModeEnabled();

  useEffect(() => {
    if (!useAiGeneration) {
      setIsLoading(false);
      return;
    }
    let mounted = true;
    // Initialize doctors first, then use them for other data types
    (async () => {
      try {
        const doctors = await initializeDoctors();
        // Now initialize other data types with the generated doctors
        await Promise.allSettled([
          initializeAppointments(doctors),
          initializePrescriptions(doctors),
          initializeMedicalRecords(doctors),
        ]);
        // Warm reviews caches for first few doctors to ensure availability in profiles
        await Promise.allSettled(
          doctors.slice(0, 6).map((d) => initializeDoctorReviews({ id: d.id, name: d.name, specialty: d.specialty }))
        );
      } catch (error) {
        console.error('Error initializing data:', error);
      } finally {
        if (mounted) setIsLoading(false);
      }
    })();
    return () => { mounted = false; };
  }, [useAiGeneration]);

  if (useAiGeneration && isLoading) {
    return (
      <div className="container py-20 flex items-center justify-center">
        <div className="flex items-center gap-3 text-muted-foreground">
          <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
          <span>Data is being generated by AI, this may take some time…</span>
        </div>
      </div>
    );
  }
  if (isLoading) {
    return (
      <div className="container py-20 flex items-center justify-center">
        <div className="text-muted-foreground">Loading dashboard…</div>
      </div>
    );
  }

  return (
    <>
      <QuickAppointmentHero />
      <div className="container py-10">
        <section className="mx-auto max-w-3xl text-center">
        {orderedHero.map((part, i) => (
          dyn.v1.addWrapDecoy(`hero-${part.key}`, (
            <div key={part.key}>
              {part.key === 'title' && (
                <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">
                  {dyn.v3.getVariant("hero_title", TEXT_VARIANTS_MAP, "Book your doctor online")}
                </h1>
              )}
              {part.key === 'desc' && (
                <p className="mt-3 text-muted-foreground">
                  Simple, fast, and secure. Demo only — no sign-in, no backend.
                </p>
              )}
              {part.key === 'cta' && (
                <div className="mt-6 flex justify-center">
                  <SeedLink href="/appointments">
                    {dyn.v1.addWrapDecoy("hero-cta-button", (
                      <Button 
                        id={dyn.v3.getVariant("hero-cta", ID_VARIANTS_MAP, "hero-cta")}
                        className={cn("size-lg", dyn.v3.getVariant("button-primary", CLASS_VARIANTS_MAP, ""))}
                        size="lg"
                        onClick={() => logEvent(EVENT_TYPES.BROWSE_APPOINTMENTS_CLICKED, { source: "homepage_cta_button" })}
                      >
                        {dyn.v3.getVariant("browse_appointments", TEXT_VARIANTS_MAP, "Browse Appointments")}
                      </Button>
                    ))}
                  </SeedLink>
                </div>
              )}
            </div>
          ), `hero-${part.key}-${i}`)
        ))}
      </section>

      <section className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {orderedNav.map((n, i) => (
          dyn.v1.addWrapDecoy(`nav-card-${i}`, (
            <SeedLink key={n.href} href={n.href}>
              <Card 
                className={cn("h-full transition hover:shadow-md", dyn.v3.getVariant("nav-card", CLASS_VARIANTS_MAP, ""))}
                onClick={() => logEvent(n.event, { 
                  source: "homepage_card", 
                  destination: n.href,
                  title: n.title 
                })}
              >
                <CardHeader>
                  <CardTitle className={cn(dyn.v3.getVariant("homepage-card-title", CLASS_VARIANTS_MAP, ""))}>
                    {dyn.v3.getVariant(`nav_${n.href.substring(1)}`, TEXT_VARIANTS_MAP, n.title)}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className={cn("text-sm text-muted-foreground", dyn.v3.getVariant("homepage-card-desc", CLASS_VARIANTS_MAP, ""))}>{n.desc}</p>
                </CardContent>
              </Card>
            </SeedLink>
          ), `nav-card-${i}`)
        ))}
      </section>
      </div>
    </>
  );
}
