# Generated by Django 5.1.6 on 2025-04-10 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={},
        ),
    ]
