# Generated by Django 5.1.6 on 2025-04-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksapp", "0002_alter_cart_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="movie",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="booksapp.movie"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(blank=True, related_name="movies", to="booksapp.genre"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="favorite_genres",
            field=models.ManyToManyField(blank=True, related_name="user_favorites", to="booksapp.genre"),
        ),
    ]
