version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/app
      - sqlite_data:/app/db
    ports:
      - "8003:8003"
    environment:
      - DEBUG=0
      - AUTO_SEED=true  # Add this line to automatically confirm seeding

volumes:
  sqlite_data: