version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/app
      - sqlite_data:/app/db
      - ./static:/app/static  # Añade esta línea
    ports:
      - "8003:8003"
    environment:
      - DEBUG=0
      - AUTO_SEED=true

volumes:
  sqlite_data: