"use client";

import { SeedLink } from "@/components/ui/SeedLink";
import { useEffect, useState, useMemo } from "react";
import { initializeDoctors } from "@/data/doctors-enhanced";
import { isDataGenerationAvailable } from "@/utils/healthDataGenerator";
import type { Doctor } from "@/data/types";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Avatar } from "@/components/ui/avatar";
import { Star } from "lucide-react";
import { logEvent, EVENT_TYPES } from "@/library/events";
import { useDynamicSystem } from "@/dynamic/shared";
import { ID_VARIANTS_MAP, CLASS_VARIANTS_MAP, TEXT_VARIANTS_MAP } from "@/dynamic/v3";
import { cn } from "@/library/utils";
import { isDbLoadModeEnabled } from "@/shared/seeded-loader";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { MEDICAL_SPECIALTIES } from "@/data/medical-specialties";

function Stars({ value }: { value: number }) {
  const stars = Array.from({ length: 5 }).map((_, i) => {
    const active = value >= i + 1 - 1e-6 || value > i && value < i + 1; // show full for simplicity
    return (
      <Star key={i} className={`h-4 w-4 ${active ? "fill-yellow-400 text-yellow-500" : "text-muted-foreground"}`} />
    );
  });
  return <div className="flex items-center gap-1">{stars}</div>;
}

export default function DoctorsPage() {
  const dyn = useDynamicSystem();
  const [doctorList, setDoctorList] = useState<Doctor[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchName, setSearchName] = useState("");
  const [selectedSpecialty, setSelectedSpecialty] = useState<string>("");
  const useAiGeneration = isDataGenerationAvailable() && !isDbLoadModeEnabled();

  const handleBookNow = (doctor: Doctor) => {
    // Log the book now event
    logEvent(EVENT_TYPES.BOOK_APPOINTMENT, {
      appointmentId: `temp-${doctor.id}`,
      doctorId: doctor.id,
      doctorName: doctor.name,
      specialty: doctor.specialty,
      rating: doctor.rating,
      date: new Date().toISOString().split('T')[0],
      time: "10:00 AM",
      action: "redirect_to_appointments",
      source: "doctors_page"
    });

    // Redirect to appointments page filtered by this doctor
    window.location.href = `/appointments?doctorId=${encodeURIComponent(doctor.id)}`;
  };

  useEffect(() => {
    let mounted = true;
    initializeDoctors()
      .then((data) => { if (mounted) setDoctorList(data); })
      .finally(() => { if (mounted) setIsLoading(false); });
    return () => { mounted = false; };
  }, []);
  
  // Filter doctors by name and specialty
  const filteredDoctors = useMemo(() => {
    let filtered = doctorList;

    // Filter by name (case-insensitive)
    if (searchName.trim()) {
      const searchTerm = searchName.toLowerCase();
      filtered = filtered.filter(doctor =>
        doctor.name.toLowerCase().includes(searchTerm)
      );
    }

    // Filter by specialty
    if (selectedSpecialty) {
      filtered = filtered.filter(doctor =>
        doctor.specialty.toLowerCase() === selectedSpecialty.toLowerCase()
      );
    }

    return filtered;
  }, [doctorList, searchName, selectedSpecialty]);

  const orderedDoctors = useMemo(() => {
    const order = dyn.v1.changeOrderElements("doctors-list", filteredDoctors.length);
    return order.map((idx) => filteredDoctors[idx]);
  }, [dyn.seed, filteredDoctors]);

  if (useAiGeneration && isLoading) {
    return (
      <div className="container py-20 flex items-center justify-center">
        <div className="flex items-center gap-3 text-muted-foreground">
          <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
          <span>Data is being generated by AI, this may take some time…</span>
        </div>
      </div>
    );
  }
  if (isLoading) {
    return (
      <div className="container py-20 flex items-center justify-center">
        <div className="text-muted-foreground">Loading doctors…</div>
      </div>
    );
  }

  return (
    <>
      {/* Hero Section with Filters */}
      <section 
        className="relative min-h-[280px] flex items-center justify-center bg-cover bg-no-repeat"
        style={{
          backgroundImage: "url('/images/doctors.jpg')",
          backgroundPosition: "center top",
        }}
      >
        {/* Dark overlay for better readability */}
        <div className="absolute inset-0 bg-black/60" />
        
        {/* Content */}
        <div className="relative z-10 container mx-auto px-4 py-6">
          <div className="max-w-6xl mx-auto">
            {dyn.v1.addWrapDecoy("doctors-page-header", (
              <h1 className="text-2xl md:text-3xl font-bold text-white mb-4 text-center">Doctors</h1>
            ))}
            
            {/* Search and Filter Section */}
            <div className="p-4 md:p-6">
              <div className="grid gap-4 md:grid-cols-2">
                {/* Name Search */}
                <div className="space-y-2">
                  <Label htmlFor="doctor-name-search" className="text-sm font-medium text-white">Search by Name</Label>
                  <Input
                    id="doctor-name-search"
                    type="text"
                    placeholder="Enter doctor's name..."
                    value={searchName}
                    onChange={(e) => setSearchName(e.target.value)}
                    className={cn(dyn.v3.getVariant("input", CLASS_VARIANTS_MAP, ""))}
                  />
                </div>

                {/* Specialty Filter */}
                <div className="space-y-2">
                  <Label htmlFor="doctor-specialty-filter" className="text-sm font-medium text-white">Filter by Specialty</Label>
                  <select
                    id="doctor-specialty-filter"
                    value={selectedSpecialty}
                    onChange={(e) => setSelectedSpecialty(e.target.value)}
                    className={cn(
                      "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
                      dyn.v3.getVariant("input", CLASS_VARIANTS_MAP, "")
                    )}
                  >
                    <option value="">All Specialties</option>
                    {MEDICAL_SPECIALTIES.sort().map((specialty) => (
                      <option key={specialty} value={specialty}>
                        {specialty}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              {/* Results count */}
              <div className="mt-4 text-sm text-white">
                Showing {orderedDoctors.length} of {doctorList.length} doctors
                {searchName && ` matching "${searchName}"`}
                {selectedSpecialty && ` in ${selectedSpecialty}`}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Doctors Grid */}
      <div className="container py-10">

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {orderedDoctors.map((d, i) => (
          dyn.v1.addWrapDecoy(`doctor-card-${i}`, (
            <Card key={d.id} className={cn("flex flex-col w-full", dyn.v3.getVariant("doctor-card", CLASS_VARIANTS_MAP, ""))}>
              <CardHeader className="flex-row items-center gap-4">
                <Avatar name={d.name} />
                <div>
                  <CardTitle className="text-lg">{d.name}</CardTitle>
                  <div className="text-sm text-muted-foreground">{d.specialty}</div>
                </div>
              </CardHeader>
              <CardContent className="pt-0">
                <Stars value={d.rating} />
                <p className="mt-3 text-sm text-muted-foreground">{d.bio}</p>
              </CardContent>
              <CardFooter className="mt-auto flex gap-2">
                <SeedLink href={`/doctors/${d.id}`}>
                  {dyn.v1.addWrapDecoy(`view-profile-button-${i}`, (
                    <Button 
                      id={dyn.v3.getVariant("view-profile-button", ID_VARIANTS_MAP, `view-profile-button-${i}`)}
                      className={cn(dyn.v3.getVariant("button-secondary", CLASS_VARIANTS_MAP, ""))}
                      variant="outline"
                      onClick={() => logEvent(EVENT_TYPES.VIEW_DOCTOR_PROFILE, {
                        doctorId: d.id,
                        doctorName: d.name,
                        specialty: d.specialty,
                        rating: d.rating
                      })}
                    >
                      {dyn.v3.getVariant("view_profile", TEXT_VARIANTS_MAP, "View Profile")}
                    </Button>
                  ))}
                </SeedLink>
                {dyn.v1.addWrapDecoy(`book-now-button-${i}`, (
                  <Button 
                    id={dyn.v3.getVariant("book-now-button", ID_VARIANTS_MAP, `book-now-button-${i}`)}
                    className={cn("bg-green-600 hover:bg-green-700", dyn.v3.getVariant("button-primary", CLASS_VARIANTS_MAP, ""))}
                    onClick={() => handleBookNow(d)}
                  >
                    {dyn.v3.getVariant("book_now", TEXT_VARIANTS_MAP, "Book Now")}
                  </Button>
                ))}
              </CardFooter>
            </Card>
          ), `doctor-card-${i}`)
        ))}
      </div>
      </div>
    </>
  );
}
