"use client";

import { SeedLink } from "@/components/ui/SeedLink";
import { useEffect, useState, useMemo } from "react";
import { initializeDoctors } from "@/data/doctors-enhanced";
import { isDataGenerationAvailable } from "@/utils/healthDataGenerator";
import type { Doctor } from "@/data/doctors";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Avatar } from "@/components/ui/avatar";
import { Star } from "lucide-react";
import { logEvent, EVENT_TYPES } from "@/library/events";
import { AppointmentBookingModal } from "@/components/appointment-booking-modal";
import { useDynamicSystem } from "@/dynamic/shared";
import { ID_VARIANTS_MAP, CLASS_VARIANTS_MAP, TEXT_VARIANTS_MAP } from "@/dynamic/v3";
import { cn } from "@/library/utils";
import { isDbLoadModeEnabled } from "@/shared/seeded-loader";

function Stars({ value }: { value: number }) {
  const stars = Array.from({ length: 5 }).map((_, i) => {
    const active = value >= i + 1 - 1e-6 || value > i && value < i + 1; // show full for simplicity
    return (
      <Star key={i} className={`h-4 w-4 ${active ? "fill-yellow-400 text-yellow-500" : "text-muted-foreground"}`} />
    );
  });
  return <div className="flex items-center gap-1">{stars}</div>;
}

export default function DoctorsPage() {
  const dyn = useDynamicSystem();
  const [doctorList, setDoctorList] = useState<Doctor[]>([]);
  const [selectedDoctor, setSelectedDoctor] = useState<Doctor | null>(null);
  const [isBookingModalOpen, setIsBookingModalOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const useAiGeneration = isDataGenerationAvailable() && !isDbLoadModeEnabled();

  const handleBookNow = (doctor: Doctor) => {
    // Log the book now event
    logEvent(EVENT_TYPES.BOOK_APPOINTMENT, {
      appointmentId: `temp-${doctor.id}`,
      doctorId: doctor.id,
      doctorName: doctor.name,
      specialty: doctor.specialty,
      rating: doctor.rating,
      date: new Date().toISOString().split('T')[0],
      time: "10:00 AM",
      action: "open_booking_modal",
      source: "doctors_page",
      modalOpenTime: new Date().toISOString()
    });

    setSelectedDoctor(doctor);
    setIsBookingModalOpen(true);
  };

  useEffect(() => {
    let mounted = true;
    initializeDoctors()
      .then((data) => { if (mounted) setDoctorList(data); })
      .finally(() => { if (mounted) setIsLoading(false); });
    return () => { mounted = false; };
  }, []);
  
  const orderedDoctors = useMemo(() => {
    const order = dyn.v1.changeOrderElements("doctors-list", doctorList.length);
    return order.map((idx) => doctorList[idx]);
  }, [dyn.seed, doctorList]);

  if (useAiGeneration && isLoading) {
    return (
      <div className="container py-20 flex items-center justify-center">
        <div className="flex items-center gap-3 text-muted-foreground">
          <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
          <span>Data is being generated by AI, this may take some time…</span>
        </div>
      </div>
    );
  }
  if (isLoading) {
    return (
      <div className="container py-20 flex items-center justify-center">
        <div className="text-muted-foreground">Loading doctors…</div>
      </div>
    );
  }

  return (
    <div className="container py-10">
      {dyn.v1.addWrapDecoy("doctors-page-header", (
        <h1 className="text-2xl font-semibold">Doctors</h1>
      ))}
      <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {orderedDoctors.map((d, i) => (
          dyn.v1.addWrapDecoy(`doctor-card-${i}`, (
            <Card key={d.id} className={cn("flex flex-col w-full", dyn.v3.getVariant("doctor-card", CLASS_VARIANTS_MAP, ""))}>
              <CardHeader className="flex-row items-center gap-4">
                <Avatar name={d.name} />
                <div>
                  <CardTitle className="text-lg">{d.name}</CardTitle>
                  <div className="text-sm text-muted-foreground">{d.specialty}</div>
                </div>
              </CardHeader>
              <CardContent className="pt-0">
                <Stars value={d.rating} />
                <p className="mt-3 text-sm text-muted-foreground">{d.bio}</p>
              </CardContent>
              <CardFooter className="mt-auto flex gap-2">
                <SeedLink href={`/doctors/${d.id}`}>
                  {dyn.v1.addWrapDecoy(`view-profile-button-${i}`, (
                    <Button 
                      id={dyn.v3.getVariant("view-profile-button", ID_VARIANTS_MAP, `view-profile-button-${i}`)}
                      className={cn(dyn.v3.getVariant("button-secondary", CLASS_VARIANTS_MAP, ""))}
                      variant="outline"
                      onClick={() => logEvent(EVENT_TYPES.VIEW_DOCTOR_PROFILE, {
                        doctorId: d.id,
                        doctorName: d.name,
                        specialty: d.specialty,
                        rating: d.rating
                      })}
                    >
                      {dyn.v3.getVariant("view_profile", TEXT_VARIANTS_MAP, "View Profile")}
                    </Button>
                  ))}
                </SeedLink>
                {dyn.v1.addWrapDecoy(`book-now-button-${i}`, (
                  <Button 
                    id={dyn.v3.getVariant("book-now-button", ID_VARIANTS_MAP, `book-now-button-${i}`)}
                    className={cn("bg-green-600 hover:bg-green-700", dyn.v3.getVariant("button-primary", CLASS_VARIANTS_MAP, ""))}
                    onClick={() => handleBookNow(d)}
                  >
                    {dyn.v3.getVariant("book_now", TEXT_VARIANTS_MAP, "Book Now")}
                  </Button>
                ))}
              </CardFooter>
            </Card>
          ), `doctor-card-${i}`)
        ))}
      </div>

      {/* Appointment Booking Modal */}
      <AppointmentBookingModal
        open={isBookingModalOpen}
        onOpenChange={setIsBookingModalOpen}
        appointment={selectedDoctor ? {
          id: `temp-${selectedDoctor.id}`,
          doctorId: selectedDoctor.id,
          doctorName: selectedDoctor.name,
          specialty: selectedDoctor.specialty,
          date: new Date().toISOString().split('T')[0],
          time: "10:00 AM"
        } : null}
      />
    </div>
  );
}
