# Generated by Django 5.1 on 2024-12-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobsapp", "0006_auto_20190408_2005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
