"use client";

import { useEffect, useRef, useState, useMemo } from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { logEvent, EVENT_TYPES } from "@/library/events";
import { initializeMedicalRecords } from "@/data/medical-records-enhanced";
import type { MedicalRecord } from "@/data/medical-records";
import { useDynamicSystem } from "@/dynamic/shared";
import { ID_VARIANTS_MAP, CLASS_VARIANTS_MAP, TEXT_VARIANTS_MAP } from "@/dynamic/v3";
import { cn } from "@/library/utils";
import { isDataGenerationAvailable } from "@/utils/healthDataGenerator";
import { isDbLoadModeEnabled } from "@/shared/seeded-loader";

export default function MedicalRecordsPage() {
  const dyn = useDynamicSystem();
  const [files, setFiles] = useState<File[]>([]);
  const [selectedCategory, setSelectedCategory] = useState<string>("all");
  const [selectedRecord, setSelectedRecord] = useState<MedicalRecord | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const [recordsList, setRecordsList] = useState<MedicalRecord[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const useAiGeneration = isDataGenerationAvailable() && !isDbLoadModeEnabled();

  function addFiles(newFiles: FileList | null) {
    if (!newFiles) return;
    const arr = Array.from(newFiles);
    setFiles((prev) => [...prev, ...arr]);
    
    // Log upload event
    logEvent(EVENT_TYPES.UPLOAD_HEALTH_DATA, {
      files: arr.map((f) => ({ 
        name: f.name, 
        type: f.type, 
        size: f.size 
      }))
    });
    
    if (fileRef.current) fileRef.current.value = "";
  }

  const handleViewRecord = (record: MedicalRecord) => {
    logEvent(EVENT_TYPES.VIEW_HEALTH_METRICS, {
      recordId: record.id,
      recordType: record.type,
      recordTitle: record.title,
      recordDate: record.date
    });
    setSelectedRecord(record);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "normal": return "bg-green-100 text-green-800";
      case "abnormal": return "bg-red-100 text-red-800";
      case "pending": return "bg-yellow-100 text-yellow-800";
      case "reviewed": return "bg-blue-100 text-blue-800";
      default: return "bg-gray-100 text-gray-800";
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case "lab_result": return "🧪";
      case "imaging": return "📷";
      case "vaccination": return "💉";
      case "visit_summary": return "📋";
      case "prescription_history": return "💊";
      case "allergy": return "⚠️";
      case "vital_signs": return "❤️";
      case "procedure": return "🏥";
      default: return "📄";
    }
  };

  const categories = ["all", "diagnostic", "preventive", "treatment", "monitoring"];
  const orderedCategories = useMemo(() => {
    const order = dyn.v1.changeOrderElements("medical-records-categories", categories.length);
    return order.map((idx) => categories[idx]);
  }, [dyn.seed, categories]);
  useEffect(() => {
    let mounted = true;
    initializeMedicalRecords()
      .then((data) => { if (mounted) setRecordsList(data); })
      .finally(() => { if (mounted) setIsLoading(false); });
    return () => { mounted = false; };
  }, []);
  const filteredRecords = selectedCategory === "all" 
    ? recordsList 
    : recordsList.filter(record => record.category === selectedCategory);
  const orderedRecords = useMemo(() => {
    const order = dyn.v1.changeOrderElements("medical-records-list", filteredRecords.length);
    return order.map((idx) => filteredRecords[idx]);
  }, [dyn.seed, filteredRecords]);

  if (useAiGeneration && isLoading) {
    return (
      <div className="container py-20 flex items-center justify-center">
        <div className="flex items-center gap-3 text-muted-foreground">
          <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
          <span>Data is being generated by AI, this may take some time…</span>
        </div>
      </div>
    );
  }
  if (isLoading) {
    return (
      <div className="container py-20 flex items-center justify-center">
        <div className="text-muted-foreground">Loading medical records…</div>
      </div>
    );
  }

  return (
    <div className="container py-10">
      <h1 className="text-2xl font-semibold">Medical Records</h1>

      {/* Category Filter */}
      <div className="mt-6 flex flex-wrap gap-2">
        {orderedCategories.map((category, i) => (
          dyn.v1.addWrapDecoy(`records-filter-${i}`, (
            <Button
              key={category}
              id={dyn.v3.getVariant(`category-filter-button-${category}`, ID_VARIANTS_MAP, `category-filter-button-${category}`)}
              className={cn(dyn.v3.getVariant("button-secondary", CLASS_VARIANTS_MAP, ""))}
              variant={selectedCategory === category ? "default" : "outline"}
              size="sm"
              onClick={() => {
                setSelectedCategory(category);
                logEvent(EVENT_TYPES.FILTER_BY_SPECIALTY, { category });
              }}
            >
              {dyn.v3.getVariant(`filter_${category}`, TEXT_VARIANTS_MAP, category.charAt(0).toUpperCase() + category.slice(1))}
            </Button>
          ), `records-filter-${i}`)
        ))}
      </div>

      {/* Upload Section */}
      {dyn.v1.addWrapDecoy("upload-section", (
        <div className="mt-8 max-w-xl space-y-2">
          <Label htmlFor={dyn.v3.getVariant("records-upload-input", ID_VARIANTS_MAP, "records-upload-input")}>Upload additional files (PDF or images)</Label>
          <div className="flex gap-2">
            {dyn.v1.addWrapDecoy("records-upload-input-container", (
              <Input 
                id={dyn.v3.getVariant("records-upload-input", ID_VARIANTS_MAP, "records-upload-input")} 
                type="file" 
                accept="application/pdf,image/*" 
                multiple 
                ref={fileRef}
                className={cn(dyn.v3.getVariant("input", CLASS_VARIANTS_MAP, ""))}
              />
            ))}
            {dyn.v1.addWrapDecoy("upload-record-button", (
              <Button 
                id={dyn.v3.getVariant("upload-record-button", ID_VARIANTS_MAP, "upload-record-button")}
                className={cn(dyn.v3.getVariant("button-primary", CLASS_VARIANTS_MAP, ""))}
                onClick={() => addFiles(fileRef.current?.files ?? null)}
              >
                {dyn.v3.getVariant("upload_record", TEXT_VARIANTS_MAP, "Upload Record")}
              </Button>
            ))}
          </div>
          <p className="text-sm text-muted-foreground">Files are not stored. They only appear in the list below for this session.</p>
        </div>
      ))}

      {/* Medical Records Grid */}
      <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {orderedRecords.map((record, i) => (
          dyn.v1.addWrapDecoy(`record-card-${i}`, (
            <Card key={record.id} className={cn("hover:shadow-md transition-shadow", dyn.v3.getVariant("card", CLASS_VARIANTS_MAP, ""))}>
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-2">
                    <span className="text-lg">{getTypeIcon(record.type)}</span>
                    <CardTitle className="text-base">{record.title}</CardTitle>
                  </div>
                  <Badge className={cn(getStatusColor(record.status), dyn.v3.getVariant("badge", CLASS_VARIANTS_MAP, ""))}>
                    {record.status}
                  </Badge>
                </div>
                <div className="text-sm text-muted-foreground">
                  {record.date} • {record.doctorName}
                </div>
              </CardHeader>
              <CardContent className="pt-0">
                <p className="text-sm text-muted-foreground mb-3 line-clamp-2">
                  {record.description}
                </p>
                {dyn.v1.addWrapDecoy(`view-record-button-${i}`, (
                  <Button
                    id={dyn.v3.getVariant("view-record-button", ID_VARIANTS_MAP, `view-record-button-${i}`)}
                    className={cn("w-full", dyn.v3.getVariant("button-secondary", CLASS_VARIANTS_MAP, ""))}
                    size="sm"
                    onClick={() => handleViewRecord(record)}
                  >
                    {dyn.v3.getVariant("view_record", TEXT_VARIANTS_MAP, "View Details")}
                  </Button>
                ))}
              </CardContent>
            </Card>
          ), `record-card-${i}`)
        ))}
      </div>

      {/* Uploaded Files Section */}
      {files.length > 0 && (
        <div className="mt-8">
          <h2 className="text-lg font-semibold mb-4">Uploaded Files</h2>
          <ul className="divide-y rounded-md border">
            {files.map((f, idx) => (
              <li key={`${f.name}-${idx}`} className="flex items-center justify-between gap-4 p-4">
                <div className="min-w-0">
                  <div className="truncate font-medium">{f.name}</div>
                  <div className="truncate text-sm text-muted-foreground">{f.type || "unknown"} • {(f.size / 1024).toFixed(1)} KB</div>
                </div>
                {dyn.v1.addWrapDecoy(`view-uploaded-record-button-${idx}`, (
                  <Button
                    id={dyn.v3.getVariant("view-record-button", ID_VARIANTS_MAP, `view-record-button-${idx}`)}
                    className={cn(dyn.v3.getVariant("button-secondary", CLASS_VARIANTS_MAP, ""))}
                    variant="outline"
                    onClick={() => {
                      logEvent(EVENT_TYPES.VIEW_HEALTH_METRICS, { 
                        index: idx, 
                        fileName: f.name,
                        fileType: f.type,
                        fileSize: f.size
                      });
                    }}
                  >
                    {dyn.v3.getVariant("view_record", TEXT_VARIANTS_MAP, "View Record")}
                  </Button>
                ))}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Record Detail Modal */}
      {selectedRecord && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="bg-white rounded-lg shadow-lg p-6 w-full max-w-2xl mx-4 max-h-[90vh] overflow-y-auto">
            <div className="flex items-start justify-between mb-4">
              <div className="flex items-center gap-2">
                <span className="text-2xl">{getTypeIcon(selectedRecord.type)}</span>
                <h2 className="text-xl font-semibold">{selectedRecord.title}</h2>
              </div>
              {dyn.v1.addWrapDecoy("close-modal-button", (
                <Button 
                  id={dyn.v3.getVariant("close-modal-button", ID_VARIANTS_MAP, "close-modal-button")}
                  className={cn(dyn.v3.getVariant("button-secondary", CLASS_VARIANTS_MAP, ""))}
                  variant="outline" 
                  onClick={() => setSelectedRecord(null)}
                >
                  {dyn.v3.getVariant("close", TEXT_VARIANTS_MAP, "Close")}
                </Button>
              ))}
            </div>
            
            <div className="space-y-4">
              {(() => {
                const infoBlocks = [
                  { key: 'meta' },
                  { key: 'desc' },
                  { key: 'values' },
                ];
                const order = dyn.v1.changeOrderElements("record-modal-blocks", infoBlocks.length);
                const orderedBlocks = order.map((idx) => infoBlocks[idx]);
                return orderedBlocks.map((b, bi) => 
                  dyn.v1.addWrapDecoy(`record-modal-block-${bi}`, (
                    <div key={b.key}>
                      {b.key === 'meta' && (
                        <div className="grid grid-cols-2 gap-4 text-sm">
                          <div><span className="font-medium">Date:</span> {selectedRecord.date}</div>
                          <div><span className="font-medium">Doctor:</span> {selectedRecord.doctorName}</div>
                          <div><span className="font-medium">Facility:</span> {selectedRecord.facility}</div>
                          <div>
                            <span className="font-medium">Status:</span>
                            <Badge className={cn("ml-2", getStatusColor(selectedRecord.status), dyn.v3.getVariant("badge", CLASS_VARIANTS_MAP, ""))}>{selectedRecord.status}</Badge>
                          </div>
                        </div>
                      )}
                      {b.key === 'desc' && (
                        <div>
                          <span className="font-medium">Description:</span>
                          <p className="mt-1 text-muted-foreground">{selectedRecord.description}</p>
                        </div>
                      )}
                      {b.key === 'values' && selectedRecord.values && (
                        <div>
                          <span className="font-medium">Results/Values:</span>
                          <div className="mt-2 grid grid-cols-1 md:grid-cols-2 gap-2">
                            {Object.entries(selectedRecord.values).map(([key, value]) => (
                              <div key={key} className="flex justify-between p-2 bg-gray-50 rounded">
                                <span className="font-medium">{key}:</span>
                                <span>{value}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  ), `record-modal-block-wrap-${bi}`)
                );
              })()}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
