repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files # Prevent large files from being committed
      - id: trailing-whitespace # Remove trailing whitespace
      - id: end-of-file-fixer # Ensure files end with a newline
      - id: mixed-line-ending # Ensure consistent line endings (LF or CRLF)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.10.0
    hooks:
      - id: ruff
        args: [ "--fix", "--line-length", "200" ]

      - id: ruff-format
        args: [ "--line-length", "200" ]
