# Generated by Django 5.1 on 2024-12-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("registration", "User Registration"),
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("password_change", "Password Change"),
                    ("profile_update", "Profile Update"),
                    ("job_application", "Job Application"),
                    ("job_post_creation", "Job Post Creation"),
                    ("job_post_update", "Job Post Update"),
                    ("job_post_deletion", "Job Post Deletion"),
                    ("resume_upload", "Resume Upload"),
                    ("newsletter_subscription", "Newsletter Subscription"),
                    ("newsletter_unsubscription", "Newsletter Unsubscription"),
                    ("message_sent", "Message Sent"),
                    ("message_received", "Message Received"),
                    ("page_view", "Page View"),
                    ("search", "Search"),
                ],
                max_length=50,
            ),
        ),
    ]
