services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_DYNAMIC_HTML: ${ENABLE_DYNAMIC_HTML:-false}
        ENABLE_DYNAMIC_HTML_STRUCTURE: ${ENABLE_DYNAMIC_HTML_STRUCTURE:-false}
    ports:
      - "${WEB_PORT}:8003"
    restart: always
    environment:
      - API_URL=http://app:8080
      - PORT=8003
      - NODE_ENV=production
      - ENABLE_DYNAMIC_HTML=${ENABLE_DYNAMIC_HTML:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_HTML=${ENABLE_DYNAMIC_HTML:-false}
      - ENABLE_DYNAMIC_HTML_STRUCTURE=${ENABLE_DYNAMIC_HTML_STRUCTURE:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_HTML_STRUCTURE=${ENABLE_DYNAMIC_HTML_STRUCTURE:-false}
    networks:
      - apps_net
networks:
  apps_net:
    external: true
