# Generated by Django 5.2 on 2025-04-07 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('clients', 'Clients'), ('projects', 'Projects'), ('tasks', 'Tasks'), ('documents', 'Documents'), ('calendar', 'Calendar'), ('chart', 'Chart')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('user', 'widget_type')},
            },
        ),
    ]
