# Generated by Django 5.1.6 on 2025-03-04 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_name",
                    models.CharField(choices=[("FILM_DETAIL", "Film Detail View"), ("SEARCH", "Search Performed"), ("REGISTRATION", "User Registration"), ("LOGIN", "User Login")], max_length=50),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("web_agent_id", models.IntegerField()),
                ("data", models.JSONField(default=dict)),
                ("search_query", models.CharField(blank=True, max_length=255, null=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["event_name"], name="events_even_event_n_0bdbb0_idx"),
                    models.Index(fields=["timestamp"], name="events_even_timesta_f18d0e_idx"),
                    models.Index(fields=["user"], name="events_even_user_id_e71281_idx"),
                ],
            },
        ),
    ]
