# Generated by Django 5.1.6 on 2025-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_remove_event_search_query_alter_event_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="web_agent_id",
            field=models.CharField(),
        ),
    ]
