BOOKS_DATA = [
    {
        "name": "Lidia's Italian-American Kitchen",
        "desc": 'Focusing on the Italian-American kitchen--the cooking she encountered when she first came to America as a young adolescent--Lidia pays homage to this "cuisine of adaptation born of necessity." But she transforms it subtly with her light, discriminating touch, using the authentic ingredients, not accessible to the early immigrants, which are all so readily available today. The aromatic flavors of fine Italian olive oil, imported Parmigiano-Reggiano and Gorgonzola dolce latte, fresh basil, oregano, and rosemary, sun-sweetened San Marzano tomatoes, prosciutto, and pancetta permeate the dishes she makes in her Italian-American kitchen today. And they will transform for you this time-honored cuisine, as you cook with Lidia, learning from her the many secret, sensuous touches that make her food superlative.',
        "year": 2001,
        "director": "Lidia Matticchio Bastianich",
        "cast": "Tim Robbins, Morgan Freeman, Bob Gunton",
        "duration": 464,
        "trailer_url": "https://www.bookstores.com/books/lidias-italian-american-kitchen/9780375411502",
        "rating": 4.8,
        "price": 12.90,
        "img_file": "9780375411502.jpg",
        "genres": ["Cooking"],
    },
    {
        "name": "Programming Massively Parallel Processors",
        "desc": "Programming Massively Parallel Processors: A Hands-on Approach shows both students and professionals alike the basic concepts of parallel programming and GPU architecture. Concise, intuitive, and practical, it is based on years of road-testing in the authors' own parallel computing courses",
        "year": 2022,
        "director": "Wen-Mei W. Hwu, David B. Kirk, Izzat El Hajj",
        "cast": "Marlon Brando, Al Pacino, James Caan",
        "duration": 580,
        "trailer_url": "https://www.bookstores.com/books/programming-massively-parallel-processors/9780323912310",
        "rating": 4.7,
        "price": 79.84,
        "img_file": "9780323912310.jpg",
        "genres": ["Education"],
    },
    {
        "name": "Elementary Statistics",
        "desc": "Simplifies statistics through practice and real-world applications Elementary Statistics: Picturing the World makes statistics approachable with stepped-out instruction, extensive real-life examples and exercises, and a design that fits content for each page to make the material more digestible. The text's combination of theory, pedagogy, and design helps students understand concepts and use statistics to describe and think about the world. ",
        "year": 2018,
        "director": "Ron Larson, Betsy Farber",
        "cast": "Christian Bale, Heath Ledger, Aaron Eckhart",
        "duration": 704,
        "trailer_url": "https://www.bookstores.com/books/elementary-statistics-ron-larson/9780134683416",
        "rating": 4.7,
        "price": 98.47,
        "img_file": "9780134683416.jpg",
        "genres": ["Science", "Education"],
    },
    {
        "name": "Dark Nights: Metal: Dark Knights Rising",
        "desc": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "year": 2019,
        "director": "Grant Morrison, Scott Snyder, Peter J. Tomasi, Francis Manapul (Illustrator)",
        "cast": "John Travolta, Uma Thurman, Samuel L. Jackson",
        "duration": 216,
        "trailer_url": "https://www.bookstores.com/books/dark-nights-metal-dark-knights-rising/9781401289072",
        "rating": 4.6,
        "price": 14.55,
        "img_file": "9781401289072.jpg",
        "genres": ["Story"],
    },
    {
        "name": "Case Files Family Medicine 5th Edition",
        "desc": "Publisher's Note: Products purchased from Third Party sellers are not guaranteed by the publisher for quality, authenticity, or access to any online entitlements included with the product.",
        "year": 2020,
        "director": "Eugene C. Toy, Donald Briscoe, Bruce S. Britton, Joel John Heidelbaugh",
        "cast": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
        "duration": 752,
        "trailer_url": "https://www.bookstores.com/books/case-files-family-medicine-5th-edition-eugene-c-toy/9781260468595",
        "rating": 4.5,
        "price": 44.00,
        "img_file": "9781260468595.jpg",
        "genres": ["Culture"],
    },
    {
        "name": "A Breath of Snow and Ashes",
        "desc": "The large scope of the novel allows Gabaldon to do what she does best, paint in exquisite detail the lives of her characters.",
        "year": 2005,
        "director": "Diana Gabaldon",
        "cast": "Elijah Wood, Ian McKellen, Orlando Bloom",
        "duration": 992,
        "trailer_url": "https://www.bookstores.com/books/a-breath-of-snow-and-ashes-diana-gabaldon/9780385324168",
        "rating": 4.6,
        "price": 7.47,
        "img_file": "9780385324168.jpg",
        "genres": ["Magazine"],
    },
    {
        "name": "Ettinger's Textbook of Veterinary Internal Medicine",
        "desc": "Now Ettinger's trusted, all-in-one veterinary resource is even better! Trusted by small animal veterinarians for more than 50 years, Ettinger's Textbook of Veterinary Internal Medicine adds new content on the field's leading issues and trends to its unmatched, \"gold standard\" coverage of the diagnosis and treatment of medical problems of dogs and cats. Coverage begins with the basics of veterinary medicine, followed by sections on differential diagnosis for chief complaints and for clinicopathologic abnormalities, and continues with techniques, minimally invasive interventional therapies, critical care, toxicology, diseases by body system, and comorbidities.",
        "year": 2024,
        "director": "Stephen J. Ettinger (Editor), Edward C. Feldman (Editor), Etienne Cote (Editor)",
        "cast": "Tom Hanks, Robin Wright, Gary Sinise",
        "duration": 2448,
        "trailer_url": "https://www.bookstores.com/books/ettingers-textbook-of-veterinary-internal-medicine/9780323779319",
        "rating": 4.6,
        "price": 207.02,
        "img_file": "9780323779319.jpg",
        "genres": ["Romance"],
    },
    {
        "name": "Art of Computer Programming, the, Volumes 1-4B, Boxed Set",
        "desc": 'Countless readers have spoken about the profound personal influence of Knuth\'s work. Scientists have marveled at the beauty and elegance of his analysis, while ordinary programmers have successfully applied his "cookbook" solutions to their day-to-day problems. All have admired Knuth for the breadth, clarity, accuracy, and good humor found in his books.',
        "year": 2022,
        "director": "Donald Knuth",
        "cast": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        "duration": 736,
        "trailer_url": "https://www.bookstores.com/books/art-of-computer-programming-the-volumes-1-4b-boxed-set/9780137935109",
        "rating": 4.5,
        "price": 239.92,
        "img_file": "9780137935109.jpg",
        "genres": ["Education", "Science"],
    },
    {
        "name": "Fourth Wing",
        "desc": "A #1 New York Times bestseller * Optioned for TV by Amazon Studios * Amazon Best Books of the Year, #4 * Apple Best Books of the Year 2023 * Barnes & Noble Best Fantasy Book of 2023 * NPR \"Books We Love\" 2023 * Audible Best Books of 2023 * Hudson Book of the Year * Google Play Best Books of 2023 * Indigo Best Books of 2023 * Waterstones Book of the Year finalist * Goodreads Choice Award, semi-finalist * Newsweek Staffers' Favorite Books of 2023 * Paste Magazine's Best Books of 2023.",
        "year": 2023,
        "director": "Rebecca Yarros",
        "cast": "Robert De Niro, Ray Liotta, Joe Pesci",
        "duration": 528,
        "trailer_url": "https://www.bookstores.com/books/fourth-wing-rebecca-yarros/9781649374042",
        "rating": 4.6,
        "price": 23.47,
        "img_file": "9781649374042.jpg",
        "genres": ["Education", "Science"],
    },
    {
        "name": "The Housemaid Is Watching",
        "desc": "A twisting, pulse-pounding thriller from Freida McFadden, the New York Times bestselling author of The Housemaid and The Coworker.",
        "year": 2024,
        "director": "Freida McFadden",
        "cast": "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        "duration": 400,
        "price": 15.35,
        "trailer_url": "https://www.bookstores.com/books/the-housemaid-is-watching-freida-mcfadden/9781464221132",
        "rating": 4.5,
        "img_file": "9781464221132.jpg",
        "genres": ["Education", "Science"],
    },
    {
        "name": "Atomic Habits",
        "desc": "A revolutionary guide to building good habits and breaking bad ones, backed by scientific research and real-world examples.",
        "year": 2018,
        "director": "James Clear",
        "cast": "N/A",
        "duration": 320,
        "trailer_url": "https://www.bookstores.com/books/atomic-habits/9780735211292",
        "rating": 4.7,
        "price": 14.99,
        "img_file": "9780735211292.jpg",
        "genres": ["Self-Help", "Psychology"],
    },
    {
        "name": "The Silent Patient",
        "desc": "A psychological thriller about a woman who shoots her husband and then stops speaking, and the therapist determined to uncover her motive.",
        "year": 2019,
        "director": "Alex Michaelides",
        "cast": "N/A",
        "duration": 336,
        "trailer_url": "https://www.bookstores.com/books/the-silent-patient/9781250301703",
        "rating": 4.5,
        "price": 9.99,
        "img_file": "9781250301703.jpg",
        "genres": ["Thriller", "Mystery"],
    },
    {
        "name": "Where the Crawdads Sing",
        "desc": "A murder mystery and coming-of-age story set in the marshes of North Carolina, blending nature writing with a gripping narrative.",
        "year": 2018,
        "director": "Delia Owens",
        "cast": "N/A",
        "duration": 384,
        "trailer_url": "https://www.bookstores.com/books/where-the-crawdads-sing/9780735219090",
        "rating": 4.8,
        "price": 12.50,
        "img_file": "9780735219090.jpg",
        "genres": ["Fiction", "Mystery"],
    },
    {
        "name": "Educated",
        "desc": "A memoir about a woman who grew up in a survivalist family in Idaho and went on to earn a PhD from Cambridge University.",
        "year": 2018,
        "director": "Tara Westover",
        "cast": "N/A",
        "duration": 352,
        "trailer_url": "https://www.bookstores.com/books/educated/9780399590504",
        "rating": 4.7,
        "price": 11.99,
        "img_file": "9780399590504.jpg",
        "genres": ["Memoir", "Biography"],
    },
    {
        "name": "The Midnight Library",
        "desc": "A novel about a library between life and death where each book represents a different life path the protagonist could have taken.",
        "year": 2020,
        "director": "Matt Haig",
        "cast": "N/A",
        "duration": 304,
        "trailer_url": "https://www.bookstores.com/books/the-midnight-library/9780525559474",
        "rating": 4.6,
        "price": 13.99,
        "img_file": "9780525559474.jpg",
        "genres": ["Fiction", "Fantasy"],
    },
    {
        "name": "Project Hail Mary",
        "desc": "A lone astronaut must save the earth from disaster in this science fiction adventure by the author of *The Martian*.",
        "year": 2021,
        "director": "Andy Weir",
        "cast": "N/A",
        "duration": 496,
        "trailer_url": "https://www.bookstores.com/books/project-hail-mary/9780593135204",
        "rating": 4.8,
        "price": 15.99,
        "img_file": "9780593135204.jpg",
        "genres": ["Science Fiction", "Adventure"],
    },
    {
        "name": "Caste: The Origins of Our Discontents",
        "desc": "An exploration of America's unspoken caste system and its parallels to systems in India and Nazi Germany.",
        "year": 2020,
        "director": "Isabel Wilkerson",
        "cast": "N/A",
        "duration": 496,
        "trailer_url": "https://www.bookstores.com/books/caste/9780593230251",
        "rating": 4.8,
        "price": 16.99,
        "img_file": "9780593230251.jpg",
        "genres": ["Nonfiction", "Social Science"],
    },
    {
        "name": "Klara and the Sun",
        "desc": "A dystopian novel about an AI companion who observes human behavior and questions what it means to love.",
        "year": 2021,
        "director": "Kazuo Ishiguro",
        "cast": "N/A",
        "duration": 320,
        "trailer_url": "https://www.bookstores.com/books/klara-and-the-sun/9780593318171",
        "rating": 4.4,
        "price": 14.99,
        "img_file": "9780593318171.jpg",
        "genres": ["Science Fiction", "Dystopian"],
    },
    {
        "name": "The Four Winds",
        "desc": "A historical novel about a woman's struggle to survive the Dust Bowl during the Great Depression.",
        "year": 2021,
        "director": "Kristin Hannah",
        "cast": "N/A",
        "duration": 464,
        "trailer_url": "https://www.bookstores.com/books/the-four-winds/9781250178602",
        "rating": 4.6,
        "price": 13.99,
        "img_file": "9781250178602.jpg",
        "genres": ["Historical Fiction", "Drama"],
    },
    {
        "name": "Malibu Rising",
        "desc": "A novel about four famous siblings throwing an epic party in Malibu that ends in chaos.",
        "year": 2021,
        "director": "Taylor Jenkins Reid",
        "cast": "N/A",
        "duration": 384,
        "trailer_url": "https://www.bookstores.com/books/malibu-rising/9781524798679",
        "rating": 4.3,
        "price": 12.99,
        "img_file": "9781524798679.jpg",
        "genres": ["Fiction", "Drama"],
    },
    {
        "name": "The Push",
        "desc": "A psychological thriller about motherhood and the dark secrets passed down through generations.",
        "year": 2021,
        "director": "Ashley Audrain",
        "cast": "N/A",
        "duration": 320,
        "trailer_url": "https://www.bookstores.com/books/the-push/9781984881663",
        "rating": 4.2,
        "price": 11.99,
        "img_file": "9781984881663.jpg",
        "genres": ["Thriller", "Psychological"],
    },
    {
        "name": "The Sanatorium",
        "desc": "A detective investigating a murder at a remote Swiss hotel uncovers chilling secrets.",
        "year": 2021,
        "director": "Sarah Pearse",
        "cast": "N/A",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/the-sanatorium/9780593296677",
        "rating": 4.0,
        "price": 10.99,
        "img_file": "9780593296677.jpg",
        "genres": ["Mystery", "Thriller"],
    },
    {
        "name": "The Last Thing He Told Me",
        "desc": "A woman searches for the truth after her husband disappears, leaving behind a cryptic note.",
        "year": 2021,
        "director": "Laura Dave",
        "cast": "N/A",
        "duration": 320,
        "trailer_url": "https://www.bookstores.com/books/the-last-thing-he-told-me/9781501171345",
        "rating": 4.4,
        "price": 12.99,
        "img_file": "9781501171345.jpg",
        "genres": ["Mystery", "Suspense"],
    },
    {
        "name": "Beautiful World, Where Are You",
        "desc": "A novel about friendship, love, and the search for meaning in modern life.",
        "year": 2021,
        "director": "Sally Rooney",
        "cast": "N/A",
        "duration": 368,
        "trailer_url": "https://www.bookstores.com/books/beautiful-world-where-are-you/9780374602604",
        "rating": 4.1,
        "price": 13.99,
        "img_file": "9780374602604.jpg",
        "genres": ["Fiction", "Literary"],
    },
    {
        "name": "The Lincoln Highway",
        "desc": "A road trip novel set in 1950s America, following three young men on a journey across the country.",
        "year": 2021,
        "director": "Amor Towles",
        "cast": "N/A",
        "duration": 592,
        "trailer_url": "https://www.bookstores.com/books/the-lincoln-highway/9780735222359",
        "rating": 4.5,
        "price": 16.99,
        "img_file": "9780735222359.jpg",
        "genres": ["Historical Fiction", "Adventure"],
    },
    {
        "name": "Apples Never Fall",
        "desc": "A family drama about the disappearance of a retired tennis coach and the secrets her children uncover.",
        "year": 2021,
        "director": "Liane Moriarty",
        "cast": "N/A",
        "duration": 512,
        "trailer_url": "https://www.bookstores.com/books/apples-never-fall/9781250220257",
        "rating": 4.3,
        "price": 14.99,
        "img_file": "9781250220257.jpg",
        "genres": ["Fiction", "Drama"],
    },
    {
        "name": "The Paris Apartment",
        "desc": "A thriller about a woman who investigates her half-brother's disappearance in Paris.",
        "year": 2022,
        "director": "Lucy Foley",
        "cast": "N/A",
        "duration": 368,
        "trailer_url": "https://www.bookstores.com/books/the-paris-apartment/9780063003057",
        "rating": 4.2,
        "price": 12.99,
        "img_file": "9780063003057.jpg",
        "genres": ["Thriller", "Mystery"],
    },
    {
        "name": "Book Lovers",
        "desc": "A romantic comedy about a literary agent and an editor who clash professionally but spark personally.",
        "year": 2022,
        "director": "Emily Henry",
        "cast": "N/A",
        "duration": 384,
        "trailer_url": "https://www.bookstores.com/books/book-lovers/9780593334836",
        "rating": 4.4,
        "price": 11.99,
        "img_file": "9780593334836.jpg",
        "genres": ["Romance", "Comedy"],
    },
    {
        "name": "Sea of Tranquility",
        "desc": "A time-travel novel spanning centuries, exploring art, pandemics, and human connection.",
        "year": 2022,
        "director": "Emily St. John Mandel",
        "cast": "N/A",
        "duration": 272,
        "trailer_url": "https://www.bookstores.com/books/sea-of-tranquility/9780593321447",
        "rating": 4.5,
        "price": 13.99,
        "img_file": "9780593321447.jpg",
        "genres": ["Science Fiction", "Literary"],
    },
    {
        "name": "The Psychology of Money",
        "desc": "Timeless lessons on wealth, greed, and happiness through 19 short stories exploring how people think about money.",
        "year": 2020,
        "director": "Morgan Housel",
        "cast": "N/A",
        "duration": 256,
        "trailer_url": "https://www.bookstores.com/books/psychology-of-money/9780857197689",
        "rating": 4.7,
        "price": 15.99,
        "img_file": "9780857197689.jpg",
        "genres": ["Finance", "Psychology"],
    },
    {
        "name": "Greenlights",
        "desc": "Matthew McConaughey's unconventional memoir filled with raucous stories, outlaw wisdom, and lessons learned the hard way.",
        "year": 2020,
        "director": "Matthew McConaughey",
        "cast": "N/A",
        "duration": 304,
        "trailer_url": "https://www.bookstores.com/books/greenlights/9780593139134",
        "rating": 4.6,
        "price": 18.99,
        "img_file": "9780593139134.jpg",
        "genres": ["Memoir", "Self-Help"],
    },
    {
        "name": "The Anthropocene Reviewed",
        "desc": "John Green reviews facets of the human-centered planet on a five-star scale in this deeply personal essay collection.",
        "year": 2021,
        "director": "John Green",
        "cast": "N/A",
        "duration": 304,
        "trailer_url": "https://www.bookstores.com/books/anthropocene-reviewed/9780525555216",
        "rating": 4.8,
        "price": 16.99,
        "img_file": "9780525555216.jpg",
        "genres": ["Essays", "Nonfiction"],
    },
    {
        "name": "Crying in H Mart",
        "desc": "A memoir about grief, love, and identity through the lens of food and the author's Korean-American upbringing.",
        "year": 2021,
        "director": "Michelle Zauner",
        "cast": "N/A",
        "duration": 256,
        "trailer_url": "https://www.bookstores.com/books/crying-in-h-mart/9780525657743",
        "rating": 4.7,
        "price": 14.99,
        "img_file": "9780525657743.jpg",
        "genres": ["Memoir", "Biography"],
    },
    {
        "name": "The Song of Achilles",
        "desc": "A retelling of the Iliad from Patroclus's perspective, exploring his relationship with Achilles.",
        "year": 2012,
        "director": "Madeline Miller",
        "cast": "N/A",
        "duration": 416,
        "trailer_url": "https://www.bookstores.com/books/song-of-achilles/9780062060624",
        "rating": 4.8,
        "price": 12.99,
        "img_file": "9780062060624.jpg",
        "genres": ["Historical Fiction", "Fantasy"],
    },
    {
        "name": "Pachinko",
        "desc": "A multi-generational saga about a Korean family living in Japan, exploring identity and survival.",
        "year": 2017,
        "director": "Min Jin Lee",
        "cast": "N/A",
        "duration": 496,
        "trailer_url": "https://www.bookstores.com/books/pachinko/9781455563937",
        "rating": 4.6,
        "price": 13.99,
        "img_file": "9781455563937.jpg",
        "genres": ["Historical Fiction", "Drama"],
    },
    {
        "name": "The House in the Cerulean Sea",
        "desc": "A whimsical fantasy about a caseworker who discovers magic and love at an orphanage for magical children.",
        "year": 2020,
        "director": "TJ Klune",
        "cast": "N/A",
        "duration": 398,
        "trailer_url": "https://www.bookstores.com/books/house-cerulean-sea/9781250217318",
        "rating": 4.7,
        "price": 14.99,
        "img_file": "9781250217318.jpg",
        "genres": ["Fantasy", "LGBTQ+"],
    },
    {
        "name": "Mexican Gothic",
        "desc": "A chilling horror novel about a woman investigating her cousin's claims of a haunted mansion in 1950s Mexico.",
        "year": 2020,
        "director": "Silvia Moreno-Garcia",
        "cast": "N/A",
        "duration": 320,
        "trailer_url": "https://www.bookstores.com/books/mexican-gothic/9780525620785",
        "rating": 4.3,
        "price": 12.99,
        "img_file": "9780525620785.jpg",
        "genres": ["Horror", "Gothic"],
    },
    {
        "name": "The Invisible Life of Addie LaRue",
        "desc": "A woman makes a Faustian bargain to live forever but is cursed to be forgotten by everyone she meets.",
        "year": 2020,
        "director": "V.E. Schwab",
        "cast": "N/A",
        "duration": 448,
        "trailer_url": "https://www.bookstores.com/books/invisible-life-addie-larue/9780765387561",
        "rating": 4.5,
        "price": 15.99,
        "img_file": "9780765387561.jpg",
        "genres": ["Fantasy", "Historical Fiction"],
    },
    {
        "name": "Black Cake",
        "desc": "A family unravels secrets after their mother's death, tied to a Caribbean black cake recipe.",
        "year": 2022,
        "director": "Charmaine Wilkerson",
        "cast": "N/A",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/black-cake/9780593358337",
        "rating": 4.4,
        "price": 14.99,
        "img_file": "9780593358337.jpg",
        "genres": ["Fiction", "Family Saga"],
    },
    {
        "name": "The Seven Husbands of Evelyn Hugo",
        "desc": "A reclusive Hollywood icon reveals her scandalous life story to an unknown journalist.",
        "year": 2017,
        "director": "Taylor Jenkins Reid",
        "cast": "N/A",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/seven-husbands-evelyn-hugo/9781501161933",
        "rating": 4.7,
        "price": 12.99,
        "img_file": "9781501161933.jpg",
        "genres": ["Historical Fiction", "LGBTQ+"],
    },
    {
        "name": "Circe",
        "desc": "A reimagining of the life of Circe, the witch from Homer's Odyssey, as she discovers her power.",
        "year": 2018,
        "director": "Madeline Miller",
        "cast": "N/A",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/circe/9780316556347",
        "rating": 4.8,
        "price": 13.99,
        "img_file": "9780316556347.jpg",
        "genres": ["Fantasy", "Mythology"],
    },
    {
        "name": "The Guest List",
        "desc": "A murder mystery set at a wedding on a remote Irish island, where everyone has a motive.",
        "year": 2020,
        "director": "Lucy Foley",
        "cast": "N/A",
        "duration": 320,
        "trailer_url": "https://www.bookstores.com/books/guest-list/9780062868930",
        "rating": 4.2,
        "price": 11.99,
        "img_file": "9780062868930.jpg",
        "genres": ["Mystery", "Thriller"],
    },
    {
        "name": "Normal People",
        "desc": "A nuanced love story about two Irish teenagers navigating class, intimacy, and identity.",
        "year": 2018,
        "director": "Sally Rooney",
        "cast": "N/A",
        "duration": 288,
        "trailer_url": "https://www.bookstores.com/books/normal-people/9781984822178",
        "rating": 4.5,
        "price": 12.99,
        "img_file": "9781984822178.jpg",
        "genres": ["Fiction", "Romance"],
    },
    {
        "name": "The Vanishing Half",
        "desc": "Twin sisters choose to live in different racial worlds in this exploration of identity and family.",
        "year": 2020,
        "director": "Brit Bennett",
        "cast": "N/A",
        "duration": 352,
        "trailer_url": "https://www.bookstores.com/books/vanishing-half/9780525536291",
        "rating": 4.5,
        "price": 12.99,
        "img_file": "9780525536291.jpg",
        "genres": ["Historical Fiction", "Drama"],
    },
    {
        "name": "Such a Fun Age",
        "desc": "A witty novel about race, privilege, and the complexities of modern relationships.",
        "year": 2019,
        "director": "Kiley Reid",
        "cast": "N/A",
        "duration": 310,
        "trailer_url": "https://www.bookstores.com/books/such-a-fun-age/9780525541905",
        "rating": 4.3,
        "price": 11.99,
        "img_file": "9780525541905.jpg",
        "genres": ["Fiction", "Contemporary"],
    },
    {
        "name": "The Thursday Murder Club",
        "desc": "A group of retirees solve cold cases in this charming and clever mystery.",
        "year": 2020,
        "director": "Richard Osman",
        "cast": "N/A",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/thursday-murder-club/9781984880987",
        "rating": 4.4,
        "price": 12.99,
        "img_file": "9781984880987.jpg",
        "genres": ["Mystery", "Humor"],
    },
    {
        "name": "Hamnet",
        "desc": "A fictional account of Shakespeare's son Hamnet and the inspiration behind *Hamlet*.",
        "year": 2020,
        "director": "Maggie O'Farrell",
        "cast": "N/A",
        "duration": 320,
        "trailer_url": "https://www.bookstores.com/books/hamnet/9780525657606",
        "rating": 4.6,
        "price": 13.99,
        "img_file": "9780525657606.jpg",
        "genres": ["Historical Fiction", "Literary"],
    },
    {
        "name": "The Glass Hotel",
        "desc": "A haunting novel about greed, guilt, and the 2008 financial collapse.",
        "year": 2020,
        "director": "Emily St. John Mandel",
        "cast": "N/A",
        "duration": 320,
        "trailer_url": "https://www.bookstores.com/books/glass-hotel/9780525521143",
        "rating": 4.2,
        "price": 12.99,
        "img_file": "9780525521143.jpg",
        "genres": ["Fiction", "Literary"],
    },
    {
        "name": "Deacon King Kong",
        "desc": "A vibrant novel about a Brooklyn neighborhood in 1969 after a drunken deacon shoots a drug dealer.",
        "year": 2020,
        "director": "James McBride",
        "cast": "N/A",
        "duration": 384,
        "trailer_url": "https://www.bookstores.com/books/deacon-king-kong/9780735216723",
        "rating": 4.4,
        "price": 13.99,
        "img_file": "9780735216723.jpg",
        "genres": ["Historical Fiction", "Humor"],
    },
    {
        "name": "The City We Became",
        "desc": "A fantasy novel where New York City's boroughs come to life as human avatars fighting an ancient evil.",
        "year": 2020,
        "director": "N.K. Jemisin",
        "cast": "N/A",
        "duration": 448,
        "trailer_url": "https://www.bookstores.com/books/city-we-became/9780316509848",
        "rating": 4.3,
        "price": 14.99,
        "img_file": "9780316509848.jpg",
        "genres": ["Fantasy", "Urban Fantasy"],
    },
    {
        "name": "Transcendent Kingdom",
        "desc": "A neuroscientist grapples with faith, addiction, and family trauma in this introspective novel.",
        "year": 2020,
        "director": "Yaa Gyasi",
        "cast": "N/A",
        "duration": 288,
        "trailer_url": "https://www.bookstores.com/books/transcendent-kingdom/9780525658184",
        "rating": 4.5,
        "price": 12.99,
        "img_file": "9780525658184.jpg",
        "genres": ["Fiction", "Literary"],
    },
    {
        "name": "The Once and Future Witches",
        "desc": "A historical fantasy about three sisters who rediscover magic in 1893 New Salem.",
        "year": 2020,
        "director": "Alix E. Harrow",
        "cast": "N/A",
        "duration": 528,
        "trailer_url": "https://www.bookstores.com/books/once-future-witches/9780316422048",
        "rating": 4.4,
        "price": 15.99,
        "img_file": "9780316422048.jpg",
        "genres": ["Fantasy", "Historical Fiction"],
    },
    {
        "name": "Piranesi",
        "desc": "A surreal novel about a man who lives in a labyrinthine house filled with statues and tidal mysteries.",
        "year": 2020,
        "director": "Susanna Clarke",
        "cast": "N/A",
        "duration": 272,
        "trailer_url": "https://www.bookstores.com/books/piranesi/9781635575637",
        "rating": 4.6,
        "price": 13.99,
        "img_file": "9781635575637.jpg",
        "genres": ["Fantasy", "Mystery"],
    },
    {
        "name": "The House of Broken Angels",
        "desc": "A Mexican-American family gathers for a funeral in this sprawling, humorous, and poignant novel.",
        "year": 2018,
        "director": "Luis Alberto Urrea",
        "cast": "N/A",
        "duration": 336,
        "trailer_url": "https://www.bookstores.com/books/house-broken-angels/9780316154888",
        "rating": 4.4,
        "price": 12.99,
        "img_file": "9780316154888.jpg",
        "genres": ["Fiction", "Family Saga"],
    },
    {
        "name": "The Water Dancer",
        "desc": "A young slave with a mysterious power joins the Underground Railroad in this magical realist novel.",
        "year": 2019,
        "director": "Ta-Nehisi Coates",
        "cast": "N/A",
        "duration": 416,
        "trailer_url": "https://www.bookstores.com/books/water-dancer/9780399590597",
        "rating": 4.5,
        "price": 14.99,
        "img_file": "9780399590597.jpg",
        "genres": ["Historical Fiction", "Magical Realism"],
    },
    {
        "name": "The Nickel Boys",
        "desc": "A Pulitzer Prize-winning novel about two boys surviving a brutal reform school in Jim Crow Florida.",
        "year": 2019,
        "director": "Colson Whitehead",
        "cast": "N/A",
        "duration": 224,
        "trailer_url": "https://www.bookstores.com/books/nickel-boys/9780385537070",
        "rating": 4.7,
        "price": 12.99,
        "img_file": "9780385537070.jpg",
        "genres": ["Historical Fiction", "Literary"],
    },
    {
        "name": "The Testaments",
        "desc": "The sequel to *The Handmaid's Tale*, revealing the fates of Gilead's women.",
        "year": 2019,
        "director": "Margaret Atwood",
        "cast": "N/A",
        "duration": 432,
        "trailer_url": "https://www.bookstores.com/books/testaments/9780385543781",
        "rating": 4.5,
        "price": 14.99,
        "img_file": "9780385543781.jpg",
        "genres": ["Dystopian", "Fiction"],
    },
    {
        "name": "Daisy Jones & The Six",
        "desc": "An oral history of a fictional 1970s rock band's rise and fall, written like a documentary.",
        "year": 2019,
        "director": "Taylor Jenkins Reid",
        "cast": "N/A",
        "duration": 368,
        "trailer_url": "https://www.bookstores.com/books/daisy-jones-six/9781524798628",
        "rating": 4.6,
        "price": 13.99,
        "img_file": "9781524798628.jpg",
        "genres": ["Historical Fiction", "Music"],
    },
    {
        "name": "The Starless Sea",
        "desc": "A graduate student discovers a hidden library beneath New York in this lyrical fantasy.",
        "year": 2019,
        "director": "Erin Morgenstern",
        "cast": "N/A",
        "duration": 512,
        "trailer_url": "https://www.bookstores.com/books/starless-sea/9780385541213",
        "rating": 4.3,
        "price": 15.99,
        "img_file": "9780385541213.jpg",
        "genres": ["Fantasy", "Adventure"],
    },
    {
        "name": "The Dutch House",
        "desc": "A brother and sister reflect on their childhood in a lavish Pennsylvania mansion.",
        "year": 2019,
        "director": "Ann Patchett",
        "cast": "N/A",
        "duration": 352,
        "trailer_url": "https://www.bookstores.com/books/dutch-house/9780062963673",
        "rating": 4.5,
        "price": 12.99,
        "img_file": "9780062963673.jpg",
        "genres": ["Fiction", "Family Saga"],
    },
    {
        "name": "Red, White & Royal Blue",
        "desc": "A romantic comedy about the First Son of the U.S. falling for the Prince of Wales.",
        "year": 2019,
        "director": "Casey McQuiston",
        "cast": "N/A",
        "duration": 432,
        "trailer_url": "https://www.bookstores.com/books/red-white-royal-blue/9781250316776",
        "rating": 4.7,
        "price": 11.99,
        "img_file": "9781250316776.jpg",
        "genres": ["Romance", "LGBTQ+"],
    },
    {
        "name": "The Giver of Stars",
        "desc": "A historical novel about the Packhorse Librarians of Depression-era Kentucky.",
        "year": 2019,
        "director": "Jojo Moyes",
        "cast": "N/A",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/giver-of-stars/9780399562488",
        "rating": 4.6,
        "price": 12.99,
        "img_file": "9780399562488.jpg",
        "genres": ["Historical Fiction", "Drama"],
    },
    {
        "name": "The Institute",
        "desc": "A supernatural thriller about children with psychic abilities held captive in a sinister facility.",
        "year": 2019,
        "director": "Stephen King",
        "cast": "N/A",
        "duration": 576,
        "trailer_url": "https://www.bookstores.com/books/institute/9781982110567",
        "rating": 4.6,
        "price": 14.99,
        "img_file": "9781982110567.jpg",
        "genres": ["Horror", "Thriller"],
    },
    {
        "name": "The Ten Thousand Doors of January",
        "desc": "A young girl discovers magical doors to other worlds in this lyrical adventure.",
        "year": 2019,
        "director": "Alix E. Harrow",
        "cast": "N/A",
        "duration": 384,
        "trailer_url": "https://www.bookstores.com/books/ten-thousand-doors-january/9780316421997",
        "rating": 4.4,
        "price": 13.99,
        "img_file": "9780316421997.jpg",
        "genres": ["Fantasy", "Adventure"],
    },
    {
        "name": "The Only Plane in the Sky",
        "desc": "An oral history of 9/11, compiled from hundreds of interviews with survivors and witnesses.",
        "year": 2019,
        "director": "Garrett M. Graff",
        "cast": "N/A",
        "duration": 512,
        "trailer_url": "https://www.bookstores.com/books/only-plane-in-sky/9781501182204",
        "rating": 4.9,
        "price": 18.99,
        "img_file": "9781501182204.jpg",
        "genres": ["History", "Nonfiction"],
    },
    {
        "name": "The Body",
        "desc": "A guide to human anatomy and health, blending science with Bill Bryson's signature wit.",
        "year": 2019,
        "director": "Bill Bryson",
        "cast": "N/A",
        "duration": 464,
        "trailer_url": "https://www.bookstores.com/books/body/9780385539302",
        "rating": 4.7,
        "price": 16.99,
        "img_file": "9780385539302.jpg",
        "genres": ["Science", "Health"],
    },
    {
        "name": "Maybe You Should Talk to Someone",
        "desc": "A therapist shares insights from her own therapy sessions and her patients' journeys.",
        "year": 2019,
        "director": "Lori Gottlieb",
        "cast": "N/A",
        "duration": 432,
        "trailer_url": "https://www.bookstores.com/books/maybe-you-should-talk/9781328662057",
        "rating": 4.8,
        "price": 15.99,
        "img_file": "9781328662057.jpg",
        "genres": ["Psychology", "Memoir"],
    },
    {
        "name": "Talking to Strangers",
        "desc": "Malcolm Gladwell explores why interactions with strangers often go wrong, using psychology and case studies.",
        "year": 2019,
        "director": "Malcolm Gladwell",
        "cast": "N/A",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/talking-to-strangers/9780316478526",
        "rating": 4.5,
        "price": 14.99,
        "img_file": "9780316478526.jpg",
        "genres": ["Psychology", "Nonfiction"],
    },
    {
        "name": "The Witches Are Coming",
        "desc": "A sharp cultural critique from Lindy West, tackling misogyny, pop culture, and politics.",
        "year": 2019,
        "director": "Lindy West",
        "cast": "N/A",
        "duration": 288,
        "trailer_url": "https://www.bookstores.com/books/witches-are-coming/9780316449885",
        "rating": 4.3,
        "price": 12.99,
        "img_file": "9780316449885.jpg",
        "genres": ["Feminism", "Essays"],
    },
    {
        "name": "The Education of an Idealist",
        "desc": "Samantha Power's memoir about her journey from war correspondent to U.S. Ambassador to the UN.",
        "year": 2019,
        "director": "Samantha Power",
        "cast": "N/A",
        "duration": 592,
        "trailer_url": "https://www.bookstores.com/books/education-of-idealist/9780062820693",
        "rating": 4.7,
        "price": 17.99,
        "img_file": "9780062820693.jpg",
        "genres": ["Memoir", "Politics"],
    },
    {
        "name": "The Moment of Lift",
        "desc": "Melinda Gates shares stories of women who inspired her philanthropic work on global gender equality.",
        "year": 2019,
        "director": "Melinda Gates",
        "cast": "N/A",
        "duration": 288,
        "trailer_url": "https://www.bookstores.com/books/moment-of-lift/9781250257727",
        "rating": 4.6,
        "price": 15.99,
        "img_file": "9781250257727.jpg",
        "genres": ["Nonfiction", "Feminism"],
    },
    {
        "name": "The Second Mountain",
        "desc": "David Brooks explores the shift from self-centered success to a life of deeper relationships and purpose.",
        "year": 2019,
        "director": "David Brooks",
        "cast": "N/A",
        "duration": 384,
        "trailer_url": "https://www.bookstores.com/books/second-mountain/9780812993264",
        "rating": 4.5,
        "price": 16.99,
        "img_file": "9780812993264.jpg",
        "genres": ["Self-Help", "Philosophy"],
    },
    {
        "name": "The Right Stuff",
        "desc": "Tom Wolfe's classic account of the early U.S. space program and the Mercury astronauts.",
        "year": 1979,
        "director": "Tom Wolfe",
        "cast": "N/A",
        "duration": 352,
        "trailer_url": "https://www.bookstores.com/books/right-stuff/9780312427566",
        "rating": 4.7,
        "price": 12.99,
        "img_file": "9780312427566.jpg",
        "genres": ["History", "Science"],
    },
    {
        "name": "The Sixth Extinction",
        "desc": "A Pulitzer Prize-winning exploration of mass extinctions and humanity's role in the current biodiversity crisis.",
        "year": 2014,
        "director": "Elizabeth Kolbert",
        "cast": "N/A",
        "duration": 336,
        "trailer_url": "https://www.bookstores.com/books/sixth-extinction/9780805092998",
        "rating": 4.6,
        "price": 13.99,
        "img_file": "9780805092998.jpg",
        "genres": ["Science", "Environment"],
    },
    {
        "name": "The Emperor of All Maladies",
        "desc": "A biography of cancer, blending history, science, and personal narratives.",
        "year": 2010,
        "director": "Siddhartha Mukherjee",
        "cast": "N/A",
        "duration": 592,
        "trailer_url": "https://www.bookstores.com/books/emperor-all-maladies/9781439107959",
        "rating": 4.8,
        "price": 16.99,
        "img_file": "9781439107959.jpg",
        "genres": ["Science", "Medical"],
    },
    {
        "name": "The Warmth of Other Suns",
        "desc": "A sweeping history of the Great Migration of African Americans from the South to northern cities.",
        "year": 2010,
        "director": "Isabel Wilkerson",
        "cast": "N/A",
        "duration": 640,
        "trailer_url": "https://www.bookstores.com/books/warmth-other-suns/9780679444329",
        "rating": 4.8,
        "price": 18.99,
        "img_file": "9780679444329.jpg",
        "genres": ["History", "Nonfiction"],
    },
    {
        "name": "The Immortal Life of Henrietta Lacks",
        "desc": "The story of Henrietta Lacks, whose cancer cells were harvested without consent and revolutionized medicine.",
        "year": 2010,
        "director": "Rebecca Skloot",
        "cast": "N/A",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/immortal-life-henrietta-lacks/9781400052189",
        "rating": 4.7,
        "price": 14.99,
        "img_file": "9781400052189.jpg",
        "genres": ["Science", "Biography"],
    },
    {
        "name": "The Power of Habit",
        "desc": "An exploration of how habits shape our lives and how they can be changed.",
        "year": 2012,
        "director": "Charles Duhigg",
        "cast": "N/A",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/power-of-habit/9780812981605",
        "rating": 4.6,
        "price": 13.99,
        "img_file": "9780812981605.jpg",
        "genres": ["Psychology", "Self-Help"],
    },
    {
        "name": "Quiet",
        "desc": "A groundbreaking book about introversion and how society undervalues quiet thinkers.",
        "year": 2012,
        "director": "Susan Cain",
        "cast": "N/A",
        "duration": 352,
        "trailer_url": "https://www.bookstores.com/books/quiet/9780307352156",
        "rating": 4.6,
        "price": 12.99,
        "img_file": "9780307352156.jpg",
        "genres": ["Psychology", "Nonfiction"],
    },
    {
        "name": "Thinking, Fast and Slow",
        "desc": "Nobel laureate Daniel Kahneman explains the two systems that drive human thought.",
        "year": 2011,
        "director": "Daniel Kahneman",
        "cast": "N/A",
        "duration": 512,
        "trailer_url": "https://www.bookstores.com/books/thinking-fast-slow/9780374533557",
        "rating": 4.7,
        "price": 16.99,
        "img_file": "9780374533557.jpg",
        "genres": ["Psychology", "Science"],
    },
    {
        "name": "The Art of French Baking",
        "desc": "A comprehensive guide to mastering the delicate techniques of French pastries, from croissants to macarons. Perfect for both beginners and seasoned bakers.",
        "year": 2017,
        "director": "Julia Child",
        "cast": "Meryl Streep, Stanley Tucci, Amy Adams",
        "duration": 320,
        "trailer_url": "https://www.bookstores.com/books/the-art-of-french-baking/9780307273482",
        "rating": 4.9,
        "price": 24.99,
        "img_file": "9780307273482.jpg",
        "genres": ["Cooking", "Baking"],
    },
    {
        "name": "Deep Learning for Beginners",
        "desc": "An accessible introduction to deep learning concepts, neural networks, and AI applications. Includes hands-on exercises with Python.",
        "year": 2021,
        "director": "Andrew Ng",
        "cast": "Keanu Reeves, Carrie-Anne Moss, Laurence Fishburne",
        "duration": 420,
        "trailer_url": "https://www.bookstores.com/books/deep-learning-for-beginners/9780262039515",
        "rating": 4.7,
        "price": 49.99,
        "img_file": "9780262039515.jpg",
        "genres": ["Education", "Technology"],
    },
    {
        "name": "Astrophysics for People in a Hurry",
        "desc": "Neil deGrasse Tyson breaks down the mysteries of the cosmos into bite-sized, digestible pieces for busy readers.",
        "year": 2017,
        "director": "Neil deGrasse Tyson",
        "cast": "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        "duration": 224,
        "trailer_url": "https://www.bookstores.com/books/astrophysics-for-people-in-a-hurry/9780393609394",
        "rating": 4.8,
        "price": 12.99,
        "img_file": "9780393609394.jpg",
        "genres": ["Science", "Astronomy"],
    },
    {
        "name": "The Plant Paradox",
        "desc": "Dr. Steven Gundry reveals how so-called 'healthy' foods like grains and legumes contain harmful lectins that damage health.",
        "year": 2017,
        "director": "Steven R. Gundry",
        "cast": "Tom Hanks, Tim Allen, Annie Potts",
        "duration": 416,
        "trailer_url": "https://www.bookstores.com/books/the-plant-paradox/9780062427137",
        "rating": 4.4,
        "price": 18.99,
        "img_file": "9780062427137.jpg",
        "genres": ["Health", "Nutrition"],
    },
    {
        "name": "Becoming",
        "desc": "Michelle Obama's memoir chronicling her journey from the South Side of Chicago to the White House.",
        "year": 2018,
        "director": "Michelle Obama",
        "cast": "Viola Davis, Octavia Spencer, Emma Stone",
        "duration": 448,
        "trailer_url": "https://www.bookstores.com/books/becoming/9781524763138",
        "rating": 4.9,
        "price": 19.99,
        "img_file": "9781524763138.jpg",
        "genres": ["Biography", "Memoir"],
    },
    {
        "name": "The Lean Startup",
        "desc": "Eric Ries introduces a scientific approach to creating and managing startups for faster, more efficient product development.",
        "year": 2011,
        "director": "Eric Ries",
        "cast": "Jesse Eisenberg, Andrew Garfield, Justin Timberlake",
        "duration": 336,
        "trailer_url": "https://www.bookstores.com/books/the-lean-startup/9780307887894",
        "rating": 4.6,
        "price": 22.99,
        "img_file": "9780307887894.jpg",
        "genres": ["Business", "Entrepreneurship"],
    },
    {
        "name": "Sapiens: A Brief History of Humankind",
        "desc": "Yuval Noah Harari explores the history of Homo sapiens from ancient ancestors to the technological advancements of today.",
        "year": 2015,
        "director": "Yuval Noah Harari",
        "cast": "Anthony Hopkins, Jodie Foster, Scott Glenn",
        "duration": 464,
        "trailer_url": "https://www.bookstores.com/books/sapiens/9780062316097",
        "rating": 4.8,
        "price": 16.99,
        "img_file": "9780062316097.jpg",
        "genres": ["History", "Anthropology"],
    },
    {
        "name": "The Hobbit",
        "desc": "Bilbo Baggins embarks on an unexpected adventure with a group of dwarves to reclaim their mountain home from the dragon Smaug.",
        "year": 1937,
        "director": "J.R.R. Tolkien",
        "cast": "Martin Freeman, Ian McKellen, Richard Armitage",
        "duration": 310,
        "trailer_url": "https://www.bookstores.com/books/the-hobbit/9780547928227",
        "rating": 4.9,
        "price": 11.99,
        "img_file": "9780547928227.jpg",
        "genres": ["Fantasy", "Adventure"],
    },
    {
        "name": "The Power of Now",
        "desc": "Eckhart Tolle's guide to spiritual enlightenment through living in the present moment.",
        "year": 1997,
        "director": "Eckhart Tolle",
        "cast": "Jim Carrey, Laura Linney, Noah Emmerich",
        "duration": 236,
        "trailer_url": "https://www.bookstores.com/books/the-power-of-now/9781577314806",
        "rating": 4.6,
        "price": 12.99,
        "img_file": "9781577314806.jpg",
        "genres": ["Spirituality", "Self-Help"],
    },
    {
        "name": "Dune",
        "desc": "A science fiction epic about Paul Atreides, heir to a noble family entrusted with the dangerous desert planet Arrakis.",
        "year": 1965,
        "director": "Frank Herbert",
        "cast": "Timothée Chalamet, Rebecca Ferguson, Oscar Isaac",
        "duration": 688,
        "trailer_url": "https://www.bookstores.com/books/dune/9780441172719",
        "rating": 4.8,
        "price": 9.99,
        "img_file": "9780441172719.jpg",
        "genres": ["Sci-Fi", "Fantasy"],
    },
    {
        "name": "The Four Agreements",
        "desc": "Don Miguel Ruiz shares ancient Toltec wisdom for personal freedom: Be impeccable with your word, don't take anything personally, don't make assumptions, and always do your best.",
        "year": 1997,
        "director": "Don Miguel Ruiz",
        "cast": "Johnny Depp, Penélope Cruz, Franka Potente",
        "duration": 160,
        "trailer_url": "https://www.bookstores.com/books/the-four-agreements/9781878424310",
        "rating": 4.7,
        "price": 10.99,
        "img_file": "9781878424310.jpg",
        "genres": ["Self-Help", "Spirituality"],
    },
    {
        "name": "The Alchemist",
        "desc": "Santiago, a young Andalusian shepherd, dreams of finding worldly treasure and embarks on a journey that teaches him the true meaning of life.",
        "year": 1988,
        "director": "Paulo Coelho",
        "cast": "Jeremy Irons, Mandy Patinkin, Robin Wright",
        "duration": 208,
        "trailer_url": "https://www.bookstores.com/books/the-alchemist/9780062315007",
        "rating": 4.8,
        "price": 9.99,
        "img_file": "9780062315007.jpg",
        "genres": ["Fiction", "Philosophy"],
    },
    {
        "name": "The Girl on the Train",
        "desc": "Rachel Watson becomes entangled in a missing persons investigation after witnessing something shocking from her daily train commute.",
        "year": 2015,
        "director": "Paula Hawkins",
        "cast": "Emily Blunt, Haley Bennett, Rebecca Ferguson",
        "duration": 336,
        "trailer_url": "https://www.bookstores.com/books/the-girl-on-the-train/9781594634024",
        "rating": 4.3,
        "price": 12.99,
        "img_file": "9781594634024.jpg",
        "genres": ["Thriller", "Mystery"],
    },
    {
        "name": "The 7 Habits of Highly Effective People",
        "desc": "Stephen R. Covey presents a principle-centered approach for solving personal and professional problems.",
        "year": 1989,
        "director": "Stephen R. Covey",
        "cast": "Tom Cruise, Demi Moore, Jack Nicholson",
        "duration": 384,
        "trailer_url": "https://www.bookstores.com/books/the-7-habits/9780743269513",
        "rating": 4.6,
        "price": 16.99,
        "img_file": "9780743269513.jpg",
        "genres": ["Self-Help", "Business"],
    },
    {
        "name": "The Martian",
        "desc": "Astronaut Mark Watney is stranded on Mars and must use his ingenuity to survive while NASA works to bring him home.",
        "year": 2011,
        "director": "Andy Weir",
        "cast": "Matt Damon, Jessica Chastain, Kristen Wiig",
        "duration": 384,
        "trailer_url": "https://www.bookstores.com/books/the-martian/9780553418026",
        "rating": 4.7,
        "price": 13.99,
        "img_file": "9780553418026.jpg",
        "genres": ["Sci-Fi", "Adventure"],
    },
    {
        "name": "The Subtle Art of Not Giving a F*ck",
        "desc": "Mark Manson challenges conventional self-help advice with a counterintuitive approach to living a good life.",
        "year": 2016,
        "director": "Mark Manson",
        "cast": "Ryan Reynolds, Morena Baccarin, T.J. Miller",
        "duration": 224,
        "trailer_url": "https://www.bookstores.com/books/the-subtle-art/9780062457714",
        "rating": 4.5,
        "price": 14.99,
        "img_file": "9780062457714.jpg",
        "genres": ["Self-Help", "Humor"],
    },
    {
        "name": "The Night Circus",
        "desc": "Two young magicians, Celia and Marco, are bound in a magical competition within the enchanting Le Cirque des Rêves.",
        "year": 2011,
        "director": "Erin Morgenstern",
        "cast": "Emma Watson, Dan Stevens, Luke Evans",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/the-night-circus/9780385534635",
        "rating": 4.4,
        "price": 12.99,
        "img_file": "9780385534635.jpg",
        "genres": ["Fantasy", "Romance"],
    },
    {
        "name": "Born a Crime",
        "desc": "Trevor Noah's memoir about growing up biracial in apartheid South Africa, with a rebellious mother who defied the system.",
        "year": 2016,
        "director": "Trevor Noah",
        "cast": "Lupita Nyong'o, David Oyelowo, Madina Nalwanga",
        "duration": 304,
        "trailer_url": "https://www.bookstores.com/books/born-a-crime/9780399588174",
        "rating": 4.8,
        "price": 15.99,
        "img_file": "9780399588174.jpg",
        "genres": ["Memoir", "Humor"],
    },
    {
        "name": "The Book Thief",
        "desc": "Liesel Meminger steals books under Nazi Germany, sharing them with her neighbors and the Jewish man hidden in her basement.",
        "year": 2005,
        "director": "Markus Zusak",
        "cast": "Sophie Nélisse, Geoffrey Rush, Emily Watson",
        "duration": 584,
        "trailer_url": "https://www.bookstores.com/books/the-book-thief/9780375831003",
        "rating": 4.7,
        "price": 11.99,
        "img_file": "9780375831003.jpg",
        "genres": ["Historical Fiction", "Drama"],
    },
    {
        "name": "The Handmaid's Tale",
        "desc": "In a dystopian future, Offred navigates life as a Handmaid in the oppressive Republic of Gilead.",
        "year": 1985,
        "director": "Margaret Atwood",
        "cast": "Elisabeth Moss, Yvonne Strahovski, Joseph Fiennes",
        "duration": 311,
        "trailer_url": "https://www.bookstores.com/books/the-handmaids-tale/9780385490818",
        "rating": 4.6,
        "price": 10.99,
        "img_file": "9780385490818.jpg",
        "genres": ["Dystopian", "Fiction"],
    },
    {
        "name": "The Five Love Languages",
        "desc": "Gary Chapman explains how people express and receive love differently through words, acts, gifts, time, or touch.",
        "year": 1992,
        "director": "Gary Chapman",
        "cast": "Ryan Gosling, Rachel McAdams, James Garner",
        "duration": 208,
        "trailer_url": "https://www.bookstores.com/books/the-five-love-languages/9780802412706",
        "rating": 4.7,
        "price": 12.99,
        "img_file": "9780802412706.jpg",
        "genres": ["Relationships", "Self-Help"],
    },
    {
        "name": "The Da Vinci Code",
        "desc": "Robert Langdon and Sophie Neveu unravel clues hidden in Leonardo da Vinci's works to solve a murder and uncover a religious mystery.",
        "year": 2003,
        "director": "Dan Brown",
        "cast": "Tom Hanks, Audrey Tautou, Ian McKellen",
        "duration": 489,
        "trailer_url": "https://www.bookstores.com/books/the-da-vinci-code/9780307474278",
        "rating": 4.2,
        "price": 9.99,
        "img_file": "9780307474278.jpg",
        "genres": ["Mystery", "Thriller"],
    },
    {
        "name": "The Road",
        "desc": "A father and son journey through a post-apocalyptic America, struggling to survive in a desolate world.",
        "year": 2006,
        "director": "Cormac McCarthy",
        "cast": "Viggo Mortensen, Kodi Smit-McPhee, Charlize Theron",
        "duration": 241,
        "trailer_url": "https://www.bookstores.com/books/the-road/9780307387899",
        "rating": 4.3,
        "price": 10.99,
        "img_file": "9780307387899.jpg",
        "genres": ["Dystopian", "Drama"],
    },
    {
        "name": "The Giver",
        "desc": "Jonas lives in a seemingly perfect society without pain or war—until he is chosen to receive dark truths from The Giver.",
        "year": 1993,
        "director": "Lois Lowry",
        "cast": "Brenton Thwaites, Jeff Bridges, Meryl Streep",
        "duration": 240,
        "trailer_url": "https://www.bookstores.com/books/the-giver/9780544336261",
        "rating": 4.6,
        "price": 8.99,
        "img_file": "9780544336261.jpg",
        "genres": ["Dystopian", "Young Adult"],
    },
    {
        "name": "The Tipping Point",
        "desc": "Malcolm Gladwell examines how small actions can trigger massive social changes, epidemics, or trends.",
        "year": 2000,
        "director": "Malcolm Gladwell",
        "cast": "Jude Law, Nicole Kidman, Renée Zellweger",
        "duration": 301,
        "trailer_url": "https://www.bookstores.com/books/the-tipping-point/9780316346627",
        "rating": 4.5,
        "price": 12.99,
        "img_file": "9780316346627.jpg",
        "genres": ["Sociology", "Psychology"],
    },
    {
        "name": "The Name of the Wind",
        "desc": "Kvothe, a legendary wizard, recounts his life story—from childhood in a troupe to his time at a magical university.",
        "year": 2007,
        "director": "Patrick Rothfuss",
        "cast": "Eddie Redmayne, Felicity Jones, David Thewlis",
        "duration": 662,
        "trailer_url": "https://www.bookstores.com/books/the-name-of-the-wind/9780756404741",
        "rating": 4.8,
        "price": 13.99,
        "img_file": "9780756404741.jpg",
        "genres": ["Fantasy", "Adventure"],
    },
    {
        "name": "The Happiness Project",
        "desc": "Gretchen Rubin spends a year test-driving wisdom from science and pop culture to improve her happiness.",
        "year": 2009,
        "director": "Gretchen Rubin",
        "cast": "Reese Witherspoon, Chris Pine, Tom Hardy",
        "duration": 320,
        "trailer_url": "https://www.bookstores.com/books/the-happiness-project/9780061583261",
        "rating": 4.3,
        "price": 11.99,
        "img_file": "9780061583261.jpg",
        "genres": ["Self-Help", "Memoir"],
    },
    {
        "name": "The Goldfinch",
        "desc": "Theo Decker survives a terrorist attack at a museum, stealing a priceless painting that shapes his turbulent life.",
        "year": 2013,
        "director": "Donna Tartt",
        "cast": "Ansel Elgort, Oakes Fegley, Nicole Kidman",
        "duration": 784,
        "trailer_url": "https://www.bookstores.com/books/the-goldfinch/9780316055437",
        "rating": 4.5,
        "price": 15.99,
        "img_file": "9780316055437.jpg",
        "genres": ["Fiction", "Drama"],
    },
    {
        "name": "The Kite Runner",
        "desc": "Amir seeks redemption for betraying his childhood friend Hassan in war-torn Afghanistan.",
        "year": 2003,
        "director": "Khaled Hosseini",
        "cast": "Khalid Abdalla, Homayoun Ershadi, Atossa Leoni",
        "duration": 372,
        "trailer_url": "https://www.bookstores.com/books/the-kite-runner/9781594631931",
        "rating": 4.7,
        "price": 10.99,
        "img_file": "9781594631931.jpg",
        "genres": ["Historical Fiction", "Drama"],
    },
    {
        "name": "The Secret",
        "desc": "Rhonda Byrne explores the law of attraction, suggesting positive thoughts can manifest desires into reality.",
        "year": 2006,
        "director": "Rhonda Byrne",
        "cast": "Jim Carrey, Steve Carell, Carol Burnett",
        "duration": 216,
        "trailer_url": "https://www.bookstores.com/books/the-secret/9781582701707",
        "rating": 4.5,
        "price": 12.99,
        "img_file": "9781582701707.jpg",
        "genres": ["Self-Help", "Spirituality"],
    },
    {
        "name": "The Help",
        "desc": "In 1960s Mississippi, Skeeter collaborates with Black maids to write a tell-all book about their experiences.",
        "year": 2009,
        "director": "Kathryn Stockett",
        "cast": "Emma Stone, Viola Davis, Octavia Spencer",
        "duration": 464,
        "trailer_url": "https://www.bookstores.com/books/the-help/9780425232200",
        "rating": 4.8,
        "price": 11.99,
        "img_file": "9780425232200.jpg",
        "genres": ["Historical Fiction", "Drama"],
    },
    {
        "name": "The Fault in Our Stars",
        "desc": "Two teenagers with cancer, Hazel and Gus, fall in love while navigating life's fragility.",
        "year": 2012,
        "director": "John Green",
        "cast": "Shailene Woodley, Ansel Elgort, Nat Wolff",
        "duration": 313,
        "trailer_url": "https://www.bookstores.com/books/the-fault-in-our-stars/9780525478812",
        "rating": 4.7,
        "price": 9.99,
        "img_file": "9780525478812.jpg",
        "genres": ["Young Adult", "Romance"],
    },
    {
        "name": "The Outsiders",
        "desc": "Ponyboy Curtis and his Greaser gang clash with the wealthy Socs in 1960s Oklahoma.",
        "year": 1967,
        "director": "S.E. Hinton",
        "cast": "C. Thomas Howell, Matt Dillon, Patrick Swayze",
        "duration": 192,
        "trailer_url": "https://www.bookstores.com/books/the-outsiders/9780140385724",
        "rating": 4.7,
        "price": 8.99,
        "img_file": "9780140385724.jpg",
        "genres": ["Young Adult", "Classic"],
    },
    {
        "name": "The War of Art",
        "desc": "Steven Pressfield identifies 'Resistance' as the enemy of creativity and offers strategies to overcome it.",
        "year": 2002,
        "director": "Steven Pressfield",
        "cast": "Matt Damon, Greg Kinnear, Eva Mendes",
        "duration": 190,
        "trailer_url": "https://www.bookstores.com/books/the-war-of-art/9780446691437",
        "rating": 4.6,
        "price": 11.99,
        "img_file": "9780446691437.jpg",
        "genres": ["Self-Help", "Writing"],
    },
    {
        "name": "The Devil in the White City",
        "desc": "Erik Larson intertwines the stories of architect Daniel Burnham and serial killer H.H. Holmes at the 1893 Chicago World's Fair.",
        "year": 2003,
        "director": "Erik Larson",
        "cast": "Leonardo DiCaprio, Jonah Hill, Margot Robbie",
        "duration": 447,
        "trailer_url": "https://www.bookstores.com/books/the-devil-in-the-white-city/9780609608449",
        "rating": 4.4,
        "price": 13.99,
        "img_file": "9780609608449.jpg",
        "genres": ["History", "True Crime"],
    },
    {
        "name": "The Stand",
        "desc": "After a pandemic wipes out most of humanity, survivors align with either good or evil in an apocalyptic showdown.",
        "year": 1978,
        "director": "Stephen King",
        "cast": "Gary Sinise, Molly Ringwald, Jamey Sheridan",
        "duration": 1153,
        "trailer_url": "https://www.bookstores.com/books/the-stand/9780307743688",
        "rating": 4.7,
        "price": 19.99,
        "img_file": "9780307743688.jpg",
        "genres": ["Horror", "Post-Apocalyptic"],
    },
    {
        "name": "The Silent Spring",
        "desc": "Rachel Carson's groundbreaking exposé on the environmental damage caused by pesticides like DDT.",
        "year": 1962,
        "director": "Rachel Carson",
        "cast": "Mark Ruffalo, Anne Hathaway, Tim Robbins",
        "duration": 400,
        "trailer_url": "https://www.bookstores.com/books/the-silent-spring/9780618249060",
        "rating": 4.6,
        "price": 14.99,
        "img_file": "9780618249060.jpg",
        "genres": ["Science", "Environment"],
    },
    {
        "name": "The Road Less Traveled",
        "desc": "M. Scott Peck explores love, spiritual growth, and discipline as paths to a fulfilling life.",
        "year": 1978,
        "director": "M. Scott Peck",
        "cast": "Robin Williams, Matt Damon, Ben Affleck",
        "duration": 315,
        "trailer_url": "https://www.bookstores.com/books/the-road-less-traveled/9780743243155",
        "rating": 4.6,
        "price": 12.99,
        "img_file": "9780743243155.jpg",
        "genres": ["Psychology", "Spirituality"],
    },
    {
        "name": "The Hunger Games",
        "desc": "Katniss Everdeen volunteers for a deadly televised competition where children fight to the death in a dystopian future.",
        "year": 2008,
        "director": "Suzanne Collins",
        "cast": "Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth",
        "duration": 374,
        "trailer_url": "https://www.bookstores.com/books/the-hunger-games/9780439023481",
        "rating": 4.7,
        "price": 10.99,
        "img_file": "9780439023481.jpg",
        "genres": ["Dystopian", "Young Adult"],
    },
    {
        "name": "The Catcher in the Rye",
        "desc": "Holden Caulfield recounts his days wandering New York City after being expelled from prep school.",
        "year": 1951,
        "director": "J.D. Salinger",
        "cast": "Daniel Radcliffe, Emma Watson, Rupert Grint",
        "duration": 234,
        "trailer_url": "https://www.bookstores.com/books/the-catcher-in-the-rye/9780316769488",
        "rating": 4.6,
        "price": 9.99,
        "img_file": "9780316769488.jpg",
        "genres": ["Classic", "Fiction"],
    },
    {
        "name": "The Innovator's Dilemma",
        "desc": "Clayton Christensen explains why successful companies fail when faced with disruptive technologies.",
        "year": 1997,
        "director": "Clayton M. Christensen",
        "cast": "Jesse Eisenberg, Andrew Garfield, Justin Timberlake",
        "duration": 286,
        "trailer_url": "https://www.bookstores.com/books/the-innovators-dilemma/9780062060242",
        "rating": 4.5,
        "price": 18.99,
        "img_file": "9780062060242.jpg",
        "genres": ["Business", "Technology"],
    },
    {
        "name": "The Omnivore's Dilemma",
        "desc": "Michael Pollan traces food chains from industrial farms to organic and hunter-gatherer meals, questioning modern diets.",
        "year": 2006,
        "director": "Michael Pollan",
        "cast": "Joaquin Phoenix, Rooney Mara, Olivia Wilde",
        "duration": 450,
        "trailer_url": "https://www.bookstores.com/books/the-omnivores-dilemma/9780143038580",
        "rating": 4.5,
        "price": 16.99,
        "img_file": "9780143038580.jpg",
        "genres": ["Health", "Nutrition"],
    },
    {
        "name": "The Sun Also Rises",
        "desc": "Jake Barnes and his disillusioned expatriate friends travel from Paris to Pamplona in post-WWI Europe.",
        "year": 1926,
        "director": "Ernest Hemingway",
        "cast": "Tyrone Power, Ava Gardner, Mel Ferrer",
        "duration": 251,
        "trailer_url": "https://www.bookstores.com/books/the-sun-also-rises/9780743297332",
        "rating": 4.3,
        "price": 8.99,
        "img_file": "9780743297332.jpg",
        "genres": ["Classic", "Fiction"],
    },
    {
        "name": "The Art of War",
        "desc": "Sun Tzu's ancient treatise on military strategy, emphasizing deception, flexibility, and understanding opponents.",
        "year": "5th century BCE",
        "director": "Sun Tzu",
        "cast": "Jet Li, Tony Leung, Zhang Ziyi",
        "duration": 273,
        "trailer_url": "https://www.bookstores.com/books/the-art-of-war/9781590302255",
        "rating": 4.6,
        "price": 7.99,
        "img_file": "9781590302255.jpg",
        "genres": ["History", "Strategy"],
    },
]
if __name__ == "__main__":
    import json

    from collections import defaultdict

    print("Length: ", len(BOOKS_DATA))
    # for b in BOOKS_DATA:
    #     print(b['name'])
    name_counts = defaultdict(list)

    for book in BOOKS_DATA:
        name_counts[book["name"]].append(book)

    duplicates_by_name = [entries for entries in name_counts.values() if len(entries) > 1]
    if len(duplicates_by_name) > 0:
        print("Total duplicate found: ", len(duplicates_by_name))
        print("Duplicates by name:")
        for group in duplicates_by_name:
            for dup in group:
                print(json.dumps(dup, indent=2))
    else:
        print("No duplicates found.")
