version: '3.8'

services:

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web1_demo_jobs_portal
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    environment:
      - POSTGRES_DB=job_portal_test_bittensor
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=autoppia_2025
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db_jobs_portal
    environment:
      - POSTGRES_PASSWORD=autoppia_2025
      - POSTGRES_USER=root
      - POSTGRES_DB=web_demo_1_job_portal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
