services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_DYNAMIC_HTML: ${ENABLE_DYNAMIC_HTML:-false}
    ports:
      - "${WEB_PORT}:8002"
    restart: always
    environment:
      - API_URL=http://app:8080
      - PORT=8002
      - NODE_ENV=production
      - ENABLE_DYNAMIC_HTML=${ENABLE_DYNAMIC_HTML:-false}
      - ENABLE_DATA_GENERATION=${ENABLE_DATA_GENERATION:-false}
    networks:
      - apps_net

networks:
  apps_net:
    external: true
