version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "8002:8002"
    volumes:
      - .:/app
      # Optional: use named volume to avoid conflicts
      - node_modules:/app/node_modules
    entrypoint: ["sh", "./entrypoint.sh"]

volumes:
  node_modules:
