version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_3_autozone
    ports:
      - "${WEB_PORT}:8002"
    volumes:
#      - .:/app
      - /app/node_modules
#    networks:
#      - app-network
#    network_mode: "host"
    restart: always

#networks:
#  app-network:
##    external: true
#    driver: bridge
