#!/bin/bash

# Test script for dynamic HTML structure implementation
echo "🧪 Testing Dynamic HTML Structure Implementation for web_3_autozone"
echo "=================================================================="

# Test 1: Static structure mode (default)
echo "📋 Test 1: Static Structure Mode (dynamic_html_structure=false)"
echo "Running setup with static structure mode..."
cd "$(dirname "$0")/.."
bash scripts/setup.sh --demo=autozone --dynamic_html_structure=false --web_port=8002

echo "✅ Static structure mode deployed. Check http://localhost:8002"
echo "   - Text content and IDs should remain constant (Structure Variation 1)"
echo "   - Try URLs: http://localhost:8002?seed-structure=1 and http://localhost:8002?seed-structure=100"
echo "   - Both should show identical text content and element IDs"
echo "   - Search placeholder should always be 'Search Autozon'"
echo "   - Cart button should always be labeled 'Cart'"
echo "   - All element IDs should match Structure Variation 1"
echo
read -p "Press Enter after testing static structure mode..."

# Test 2: Dynamic structure mode
echo "📋 Test 2: Dynamic Structure Mode (dynamic_html_structure=true)"
echo "Running setup with dynamic structure mode..."
bash scripts/setup.sh --demo=autozone --dynamic_html_structure=true --web_port=8003

echo "✅ Dynamic structure mode deployed. Check http://localhost:8003"
echo "   - Text content and IDs change based on seed-structure (1-300 mapped to 10 variations)"
echo "   - Try different seed-structure values:"
echo ""
echo "   Variation 1 (Standard Amazon Style) - seeds: 1, 11, 21, 31, ..., 291"
echo "     http://localhost:8003?seed-structure=1"
echo "     - Search: 'Search Autozon' | Cart: 'Cart' | Greeting: 'Hello, user'"
echo ""
echo "   Variation 2 (Modern Shopping Hub) - seeds: 2, 12, 22, 32, ..., 292"
echo "     http://localhost:8003?seed-structure=2"
echo "     - Search: 'What are you looking for?' | Cart: 'Basket' | Greeting: 'Welcome back'"
echo ""
echo "   Variation 3 (E-Commerce Express) - seeds: 3, 13, 23, 33, ..., 293"
echo "     http://localhost:8003?seed-structure=3"
echo "     - Search: 'Search products...' | Cart: 'Shopping Cart' | Greeting: 'Hi there'"
echo ""
echo "   Variation 4 (Shop Smart) - seeds: 4, 14, 24, 34, ..., 294"
echo "     http://localhost:8003?seed-structure=4"
echo "     - Search: 'Find what you need' | Cart: 'My Cart' | Greeting: 'Hey there'"
echo ""
echo "   Variation 5 (Quick Shop) - seeds: 5, 15, 25, 35, ..., 295"
echo "     http://localhost:8003?seed-structure=5"
echo "     - Search: 'Search our store' | Cart: 'Bag' | Greeting: 'Welcome'"
echo ""
echo "   Variation 6 (Premium Marketplace) - seeds: 6, 16, 26, 36, ..., 296"
echo "     http://localhost:8003?seed-structure=6"
echo "     - Search: 'Discover premium products' | Cart: 'Shopping Bag'"
echo ""
echo "   Extended range examples:"
echo "     http://localhost:8003?seed-structure=150  # Maps to Variation 10"
echo "     http://localhost:8003?seed-structure=200  # Maps to Variation 10"
echo "     http://localhost:8003?seed-structure=300  # Maps to Variation 10"
echo ""
read -p "Press Enter after testing dynamic structure mode..."

# Test 3: Combined mode (both dynamic HTML and dynamic structure)
echo "📋 Test 3: Combined Mode (enable_dynamic_html=true + dynamic_html_structure=true)"
echo "Running setup with both features enabled..."
bash scripts/setup.sh --demo=autozone --enable_dynamic_html=true --dynamic_html_structure=true --web_port=8004

echo "✅ Combined mode deployed. Check http://localhost:8004"
echo "   - Both layout AND text content change independently"
echo "   - Examples of combined variations:"
echo ""
echo "   http://localhost:8004?seed=5&seed-structure=2"
echo "     * seed=5 → Layout: Modern minimalist"
echo "     * seed-structure=2 → Text: Modern Shopping Hub"
echo ""
echo "   http://localhost:8004?seed=180&seed-structure=50"
echo "     * seed=180 → Layout: Ultra-wide (Layout 11)"
echo "     * seed-structure=50 → Text: Variation 10 (Express Market)"
echo ""
echo "   http://localhost:8004?seed=100&seed-structure=100"
echo "     * seed=100 → Layout varies based on formula"
echo "     * seed-structure=100 → Text: Variation 10"
echo ""
echo "   http://localhost:8004?seed=250&seed-structure=250"
echo "     * seed=250 → Layout: Magazine-style (Layout 15)"
echo "     * seed-structure=250 → Text: Variation 10"
echo ""
read -p "Press Enter after testing combined mode..."

echo "🎉 Testing complete!"
echo ""
echo "Summary of test results:"
echo "  ✓ Static structure mode: Text/IDs always use Structure Variation 1"
echo "  ✓ Dynamic structure mode: Text/IDs vary based on seed-structure (1-300 → 10 variations)"
echo "  ✓ Combined mode: Independent control of layout (seed 1-300) and text (seed-structure 1-300)"
echo ""
echo "Seed-structure mapping (1-300 → 10 variations):"
echo "  Seeds 1, 11, 21, 31, ... 291  → Variation 1 (Standard Amazon Style)"
echo "  Seeds 2, 12, 22, 32, ... 292  → Variation 2 (Modern Shopping Hub)"
echo "  Seeds 3, 13, 23, 33, ... 293  → Variation 3 (E-Commerce Express)"
echo "  Seeds 4, 14, 24, 34, ... 294  → Variation 4 (Shop Smart)"
echo "  Seeds 5, 15, 25, 35, ... 295  → Variation 5 (Quick Shop)"
echo "  Seeds 6, 16, 26, 36, ... 296  → Variation 6 (Premium Marketplace)"
echo "  Seeds 7, 17, 27, 37, ... 297  → Variation 7 (Value Store)"
echo "  Seeds 8, 18, 28, 38, ... 298  → Variation 8 (Modern Outlet)"
echo "  Seeds 9, 19, 29, 39, ... 299  → Variation 9 (Marketplace Hub)"
echo "  Seeds 10, 20, 30, 40, ... 300 → Variation 10 (Express Market)"
echo ""
echo "To switch structure mode, use:"
echo "  --dynamic_html_structure=false  (static, always variation 1)"
echo "  --dynamic_html_structure=true   (dynamic, maps 1-300 to 10 variations)"

