# Generated by Django 5.1.4 on 2025-05-11 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            ("BOOK_DETAIL", "Book Detail View"),
                            ("SEARCH_BOOK", "Search Book"),
                            ("ADD_BOOK", "Add Book"),
                            ("EDIT_BOOK", "Edit BOOK"),
                            ("DELETE_BOOK", "Delete Book"),
                            ("ADD_COMMENT_BOOK", "Add Comment"),
                            ("REGISTRATION_BOOK", "User Registration"),
                            ("LOGIN_BOOK", "User Login"),
                            ("LOGOUT_BOOK", "User Logout"),
                            ("CONTACT_BOOK", "Contact Message"),
                            ("EDIT_USER_BOOK", "Edit User Profile"),
                            ("FILTER_BOOK", "Filter Book"),
                            ("PURCHASE_BOOK", "Purchase Book"),
                            ("SHOPPING_CART", "Shopping Cart"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("web_agent_id", models.CharField()),
                ("data", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["event_name"], name="events_even_event_n_0bdbb0_idx"),
                    models.Index(fields=["timestamp"], name="events_even_timesta_f18d0e_idx"),
                    models.Index(fields=["user"], name="events_even_user_id_e71281_idx"),
                ],
            },
        ),
    ]
