# Generated by Django 5.1.6 on 2025-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(choices=[('FILM_DETAIL', 'Film Detail View'), ('SEARCH', 'Search Performed'), ('REGISTRATION', 'User Registration'), ('LOGIN', 'User Login'), ('LOGOUT', 'User lOGOUT')], max_length=50),
        ),
    ]
