# Generated by Django 5.1.6 on 2025-10-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='validator_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='web_agent_id',
            field=models.CharField(max_length=100),
        ),
    ]
