# Generated by Django 5.1.6 on 2025-04-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_event_web_agent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(
                choices=[
                    ("BOOK_DETAIL", "Book Detail View"),
                    ("SEARCH_BOOK", "Search Book"),
                    ("ADD_BOOK", "Add Book"),
                    ("EDIT_BOOK", "Edit BOOK"),
                    ("DELETE_BOOK", "Delete Book"),
                    ("ADD_COMMENT", "Add Comment"),
                    ("REGISTRATION", "User Registration"),
                    ("LOGIN", "User Login"),
                    ("LOGOUT", "User Logout"),
                    ("CONTACT", "Contact Message"),
                    ("EDIT_USER", "Edit User Profile"),
                    ("FILTER_BOOK", "Filter Book"),
                    ("PURCHASE_BOOK", "Purchase Book"),
                    ("SHOPPING_CART", "Shopping Cart"),
                ],
                max_length=50,
            ),
        ),
    ]
