# Generated by Django 5.1.6 on 2025-05-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_event_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(
                choices=[
                    ("BOOK_DETAIL", "Book Detail View"),
                    ("SEARCH_BOOK", "Search Book"),
                    ("ADD_BOOK", "Add Book"),
                    ("EDIT_BOOK", "Edit BOOK"),
                    ("DELETE_BOOK", "Delete Book"),
                    ("ADD_COMMENT_BOOK", "Add Comment"),
                    ("REGISTRATION_BOOK", "User Registration"),
                    ("LOGIN_BOOK", "User Login"),
                    ("LOGOUT_BOOK", "User Logout"),
                    ("CONTACT_BOOK", "Contact Message"),
                    ("EDIT_USER_BOOK", "Edit User Profile"),
                    ("FILTER_BOOK", "Filter Book"),
                    ("PURCHASE_BOOK", "Purchase Book"),
                    ("SHOPPING_CART", "Shopping Cart"),
                ],
                max_length=50,
            ),
        ),
    ]
