#!/usr/bin/env bash
# Regenerate .github/dependabot.yml from discovered web_* (with package.json). Use --check to verify only.
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
DEPENDABOT_FILE="$REPO_ROOT/.github/dependabot.yml"
CHECK_ONLY=false
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=true

cd "$REPO_ROOT"

# Discover web_* directories that have package.json
web_dirs=()
for d in $(find . -maxdepth 1 -type d -name 'web_*' | sed 's|^\./||' | sort); do
  [[ -f "$d/package.json" ]] && web_dirs+=("$d")
done

# Build full config by writing to a temp file (avoids newline/quoting issues)
build_config() {
  local tmp
  tmp=$(mktemp)
  trap "rm -f $tmp" EXIT
  {
    cat <<'HEADER'
# Auto-generated by scripts/update-dependabot-config.sh

version: 2
updates:
  - package-ecosystem: "npm"
    directories:
HEADER
    for d in "${web_dirs[@]}"; do
      echo "      - \"/${d}\""
    done
    cat <<'TAIL'

    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "pip"
    directory: "/webs_server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/webs_server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
TAIL
  } > "$tmp"
  cat "$tmp"
}

NEW_CONFIG=$(build_config)

if [[ "$CHECK_ONLY" == true ]]; then
  if [[ ! -f "$DEPENDABOT_FILE" ]] || [[ "$(cat "$DEPENDABOT_FILE")" != "$NEW_CONFIG" ]]; then
    echo "dependabot.yml is out of date."
    exit 1
  fi
  exit 0
fi

echo "$NEW_CONFIG" > "$DEPENDABOT_FILE"
echo "Updated $DEPENDABOT_FILE (${#web_dirs[@]} web_* directories)."
