# Generated by Django 5.1.4 on 2025-03-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="gallery"),
        ),
    ]
