services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:8008"
    restart: always
    environment:
      - API_URL=http://app:8080
      - PORT=8008
      - NODE_ENV=production
    networks:
      - apps_net

networks:
  apps_net:
    external: true
