services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_DYNAMIC_HTML: ${ENABLE_DYNAMIC_HTML:-false}
        NEXT_PUBLIC_ENABLE_DYNAMIC_HTML_STRUCTURE: ${NEXT_PUBLIC_ENABLE_DYNAMIC_HTML_STRUCTURE:-true}
    ports:
      - "127.0.0.1:${WEB_PORT}:8008"
    restart: always
    environment:
      - API_URL=http://app:8080
      - PORT=8008
      - NODE_ENV=production
      - ENABLE_DYNAMIC_HTML=${ENABLE_DYNAMIC_HTML:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_HTML=${ENABLE_DYNAMIC_HTML:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_HTML_STRUCTURE=${NEXT_PUBLIC_ENABLE_DYNAMIC_HTML_STRUCTURE:-true}
    networks:
      - apps_net

networks:
  apps_net:
    external: true
